### ISSUE TITLE
compiling on Mono

### ISSUE THREAD

**Issue by nitrofurano** [kuma4649/mml2vgm#1]
If someone tried to compile mml2vgm on Mono, and ran successfully on GNU/Linux (Ubuntu, for example), please let us know - .deb packages on Ubuntu PPA repositories are also welcome

**Comment by kuma4649** [comment]
https://www.dropbox.com/s/81mokhn03yqv3dq/mml2vgmMONO.zip?dl=0

**Comment by kuma4649** [comment]
とりあえずこれでよろしくお願いします

**Comment by kuma4649** [comment]
コマンドライン版のmvc.exeを用意しました。
mono環境上で動作するか不明ですが、
再ビルド、調整することにより、「GUI版よりは」対応しやすいかと考えております。
