### ISSUE TITLE
@ CAR 用のノイズ / noise for @ CAR

### ISSUE THREAD

**Issue by ultrasound1372** [kuma4649/mml2vgm#100]
各種チップのノイズスイッチ/モードやノイズ周波数などのコマンドをコマンドアルペジオに追加することは可能でしょうか?これはおそらく、ノートタイ間で上記のコマンドを機能させるよりも有用であると思われるでしょう。私はPSGチップ上のドラムを作る目的でこれを要求します。私が覚えているから、必要なコマンドはP、w、およびwfです。

----------

Would it be possible to add commands such as the noise switch/mode and noise frequency for the various chips to the command arpeggios? This would probably prove more useful than to make said commands work between note ties. I request this for the purpose of making drums on the PSG chips. From what I remember, the necesary commands are P, w, and wf.

**Comment by kuma4649** [comment]
対応可能かどうか調査させていただきます。

**Comment by kuma4649** [comment]
TAG394 で対応しました。
DCSG/OPM/HuCは今後対応予定です

**Comment by kuma4649** [comment]
TAG395で対応しました。

**Comment by kuma4649** [comment]
こちら、いかがでしょうか。

**Comment by kuma4649** [comment]
閉じますね。
