### ISSUE TITLE
How to define a more precise frequency for ADPCM-B?

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#104]
For example, I need the sound between o6g and o6g+, that is, the sound between semitones. Is it possible to directly define the frequency to?

**Comment by kuma4649** [comment]
opnb?

**Comment by denjhang** [comment]
OPNB

**Comment by denjhang** [comment]
OPNA

**Comment by kuma4649** [comment]
yコマンドでもダメですか？

**Comment by denjhang** [comment]
So which y command should I use?

**Comment by kuma4649** [comment]
「YM2610 application manual」で検索するとそこらへんの情報は見つかります...
アドレスはPort0の$10～$1Fのようですね...

**Comment by kuma4649** [comment]
或いはデチューンコマンドで音程をずらしてみるとか。

**Comment by denjhang** [comment]
The detuning command EXn can only be used for FM channels.

**Comment by denjhang** [comment]
△N = ( f ÷ 55.5  KHz ) × 65536

19 | Delta-N lower 8 bits | Delta-N (LSB)
1A | Delta-N upper 8 bits | Delta-N (MSB)

**Comment by denjhang** [comment]
'T19 T1 p3 @3 y$19,$6a y$1A,$cb
This only defines the frequency as 44100hz, but there is no sound. How should I excite the note?

**Comment by kuma4649** [comment]
デチューンコマンドはDです。

**Comment by kuma4649** [comment]
発音するためのシーケンスもマニュアルに載ってますけど...
yコマンドで済ますのはちょっと現実的じゃないかな...orz

**Comment by denjhang** [comment]
'@ P 1,"..\wav2\snow\snow-left-18500.wav",18500,100,YM2610B,0
'@ P 2,"..\wav2\snow\snow-right-18500.wav",18500,100,YM2610B,0
'@ P 3,"..\wav2\snow-44100.wav",,100,YM2610B,1

'T13 T0 p2  @2  c c
'T14 T0 p1  @1  c c
'T19 T1   @3 v30 o6D-1296 f+ f+

**Comment by denjhang** [comment]
ok
