### ISSUE TITLE
ASIO 使用時に mml2vgm を起動すると、オーディオインターフェイスのサンプルレートが 44.1kHz に切り替わる。

### ISSUE THREAD

**Issue by TH-884** [kuma4649/mml2vgm#106]
48,000 Hz で ASIO オーディオインターフェイスを使用していた場合、mml2vgm を起動するとオーディオインターフェイスのサンプルレートが 44.1Khz に自動で切り替わるという現象が必ず起こります。
MDPlayer ではそういった事象は発生しないのですが、仕様なのかどうなのかが気になるところです。

## 前提条件
- ASIO オーディオインターフェイスを使用
- ASIO デバイスのサンプルレートを 48000 Hz(おそらく 44.1KHz以外) に設定
- mml2vgmIDE の「オプション」->「出力」タブの Out 設定を ”AsioOut" に設定

## 再現方法
- 上記の条件を満たした状態で、mml2vgmIDE を起動する。
- ASIO デバイスのサンプルレートを確認

## 回避方法
特に AsioOut でなければならない強い理由がない限り、WaveOut 経由で ASIO オーディオインターフェイスを使用する。

以上です。
お手数ですが、ASIO I/Fをお持ちであれば現象が再現するかご確認よろしくお願いいたします。

**Comment by kuma4649** [comment]
すみません、すっかり見逃していました。。。

デフォルトのレートが切り替わってしまうということであれば、
mml2vgm,MDPlayerとも、自分に設定されたレートにASIOの設定を切り替えるからだと思います。

**Comment by TH-884** [comment]
現象が発生したバージョンについては、SampleRate を設定するドロップダウンが無かったのですが、新しいバージョンには SampleRate を設定することができるので、問題は発生しないと思われます。

参考：発生したバージョンのオプション
![image](https://user-images.githubusercontent.com/82717351/118752786-b2db6b80-b89e-11eb-8803-3e19eb049290.png)

新しいバージョンのオプション
![image](https://user-images.githubusercontent.com/82717351/118752987-0bab0400-b89f-11eb-9294-d03046f1534a.png)

ですので、この Issue についてはクローズにして構わないですね。

**Comment by TH-884** [comment]
新しいバージョンにて問題が解消されたのでクローズ
