### ISSUE TITLE
PSG PCM

### ISSUE THREAD

**Issue by ultrasound1372** [kuma4649/mml2vgm#112]
DCSGにハックされたPCM再生機能が追加されたので、AY3-8910にも追加してほしい。 これはDCSGにも当てはまることですが、再生周波数を固定にして、ハードコードされた値以外の値を設定できるようにしたいと思います。 例えば、上限を22050Hzにハードコードしておきながら、8kHz、11.025kHz、16kHzなどの波形ファイルを取り込めるようにする。 上限を設けることは、VGMの仕様上、意味があります。 余談ですが、AYの対数ボリュームコントロールのテーブルを探して、4ビットのボリュームレジスター内で再生するのに適したwavファイルをPCMにエンコードして、実質的に大きな音が出るようにしてみてはいかがでしょうか。 しかし、これがどれほど可能なのかはわかりません。

**Comment by kuma4649** [comment]
TAG434でPCM対応しました。。。音、小さいです。

**Comment by kuma4649** [comment]
こちら、いかがでしょうか

**Comment by kuma4649** [comment]
一旦閉じますね。
