### ISSUE TITLE
support nes apu?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#113]
こんにちは、
nes apuのサポートを追加することに興味がありますか？
nesにはvgm形式の拡張チップがいくつかありますが、私は主にメインチャネル（2 pulse、triangle、noise、およびdpcm）について質問しています。
あなたの考えは何ですか？

**Comment by kuma4649** [comment]
興味はあります

**Comment by kuma4649** [comment]
TAG435 にて暫定対応

**Comment by musicalman** [comment]
うわー、それは速かった！ ありがとう！
私はそれをテストし、いくつかのバグを見つけました：
1.パルスチャンネルの下部オクターブは無音です。 トライアングルチャンネルは問題ありません。
2.次のコマンドは、スタックトレースエラーを生成します。
_（曲げ）
yn1、n2（レジスタ直接書き込み）
例が必要な場合は、私に知らせてください。
また、コマンドアルペジオで@Iを使用してデューティサイクルを変更する機能についても提案があります。 これは、nes音楽で一般的な効果です。
それ以外は嬉しいです！

**Comment by kuma4649** [comment]
>1
一応調整してo1a+以降は発音するようになりました。
しかし、これはEMUだけかも知れないのですが、o1a以下は出せない設計のようです...

>2
ページ機能は当分使用できません。ごめんなさい。
yコマンド対応しましたが、特殊です。
vgmspecxxx.txtより抜粋
  NES APU, write value dd to register aa
  Note: Registers 00-1F equal NES address 4000-401F,
             registers 20-3E equal NES address 4080-409E,
             register 3F equals NES address 4023,
             registers 40-7F equal NES address 4040-407F.

DutyCycle ?

**Comment by musicalman** [comment]
情報をありがとう！
私は最初のバグをうまく説明しなかったと思います。 ページコマンドを使おうとはしていません。
バグは、たとえば、c4_gがエラーを生成することです。
デューティサイクルについて：
コマンドアルペジオでDutyCycleをサポートしたいのですが。
したがって、基本的には@iをコマンドとして使用します。

**Comment by kuma4649** [comment]
TAG437 にて対応

**Comment by musicalman** [comment]
ありがとう、すべてが順調です！
