### ISSUE TITLE
Support volume modifier?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#117]
やあ、
出力VGMファイルの音量を変更したいと思います。
VGMヘッダーにはボリューム・モディファイアを設定できるバイトがあるようです。
これはMMML2VGMで実装できますか？
理解していただけるといいのですが。

**Comment by kuma4649** [comment]
その機能は、実装予定は今のところありません。。。

**Comment by musicalman** [comment]
ああ、私は理解しています。
