### ISSUE TITLE
extended HuC6280 PCM

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#122]
こんにちは。
HuC6280のpcm機能を拡張するためのアイデアをいくつか考えてみました。
再生速度は@p定義で自由に設定できます。しかし、ノートデータは音に影響を与えず、すべてのノートが同じ音になります。そこで、@p定義でo4cのレートを指定すると、他の音もそれに合わせて調整され、メロディを奏でることができるように変更できないかと考えています。
また、サンプルループにも対応できないかと思っています。
ただ、HuC6280のpcm機能では限界があるのかもしれませんね。私にはわかりません。
だから、無理なら無理でいいんです。

**Comment by kuma4649** [comment]
PCM map機能使えませんか？

**Comment by musicalman** [comment]
そうですね、pcm Mapなら大丈夫でしょう。私はこのようにしています。
http://www.fileconvoy.com/dfl.php?id=g802b0d2097526edd10003777817d2aa0c0ee63a519
問題は重複が多いことで、サンプルのレートやピッチを変更できないため、同じサンプルが8回コピーされます。
これは、HuC6280の限界でしょうか？

**Comment by kuma4649** [comment]
HuC6280の限界がどこまでなのかわからないので、今のところ8kHz固定にしています。
PCEのmusicドライバの作り方によっては、可変周波数もある程度サポートできるかもしれませんが
そういうものを知らないので、とりあえず今はこの8ｋHz固定を基準にしています。

**Comment by musicalman** [comment]
ああ、わかりました。
不思議なのは、mml2vgmの中では、好きなレートが使えるんです。レートは無制限のようです。
もしかしたら、それはエミュレーションなどの副作用かもしれません。

**Comment by kuma4649** [comment]
？？

具体的な説明をお願いできますか？

**Comment by musicalman** [comment]
以前のコメントの中で、gwiのデータ例を掲載しました。リンクはこちらです。 http://www.fileconvoy.com/dfl.php?id=g802b0d2097526edd10003777817d2aa0c0ee63a519
このファイルでは、1つのサンプルでどのようにメロディーを演奏するかを示しています。
そのためには、各音ごとに別々のサンプルをロードする必要があります。
説明になっていますか？

**Comment by kuma4649** [comment]
あぁなるほど。
恐らく、この場合は指定された周波数固定で再生するようにコンパイルされますね。
vgmのストリームの機能が利用されていると思います。

そうか、HuCの場合は8kHzではなく、ユーザーが指定した周波数でさいせいするようにしてたんですねぇ。失礼しました。

多分、実際に実機で鳴らすことが可能な周波数がわからなかったからだと思います。。。

**Comment by kuma4649** [comment]
これはこのままで問題ないと思います。
確かにメロディを演奏するには、音階違いのPCMを用意することになります。


実際のPCEで演奏するケースを考えると、可変する周波数の仕組みを実装することは難しいと考えます。
よって、周波数を固定すると思うのですが、mml2vgmはその固定するという縛りをユーザーに委ねているということになります。

**Comment by musicalman** [comment]
ああ、それなら納得です。それならば、問題ありません。
このままでいいと思いますよ。他のサンプリングレートを選択できる可能性があるのはいいですね :)
