### ISSUE TITLE
Support K054539?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#123]
こんにちは。
私はコナミのK054539サウンドチップのサポートをお願いしています。
これはK053260の後継で、私の意見では大きく改善されています。
サポートを追加することは可能だと思いますか？お時間をいただきありがとうございます。

**Comment by musicalman** [comment]
混乱しています。K054539のエミュレーションはOPXのように未熟だとおっしゃるのですか？

**Comment by musicalman** [comment]
ああ、私はエミュレーションが悪かったことを知りませんでした。
私はそれを使うことに興奮しました。 しかし、私はあなたが快適に感じていないかどうかを理解しています。

**Comment by SaxxonPike** [comment]
Hello! I just happened to find your project while searching for K054539 filter info while I improve the DPCM support in MAME.

You may use this table of deltas for your own K054539 emulation, which I have found to be more correct and do not result in a DC offset in samples I have tried:
{ 0, 1, 2, 4, 8, 16, 32, 64, 0, -64, -32, -16, -8, -4, -2, -1 }

As for reverb, it's probably a FIR filter (like the SPC700) but we do not know the taps for it yet.

**Comment by kuma4649** [comment]
こんばんは。申し訳ありません。
音源chipの対応は基本的にvgmplayか、mameの対応を待ってそれに合わせてこちらも移植しています。
ですので、ご提案はありがたいのですが、mameの開発チームに向けていただいたほうが良いです。

**Comment by SaxxonPike** [comment]
You make a good point. So, I have contributed my changes to mame. They are now merged. I hope you can find this useful.

https://github.com/mamedev/mame/pull/9778
