### ISSUE TITLE
secondary chips

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#129]
こんにちは。
セカンダリーチップを使おうとすると、いくつかの問題があることがわかりました。
Ay3では、2つのチップを同時に使って音を出すことができないのです。片方のチップがもう片方のチップを切ってしまうのです。
また、セカンダリチップにサンプルデータを読み込んでもうまくいかないようです。vgm出力ファイルは再生されません。
SegaPCM、C140、RF5Cなどで試してみました。
これらの挙動が確認できるテスト用GWIデータを以下に示します。 http://www.fileconvoy.com/dfl.php?id=g6b80bfe1c531cb951000409006759574f18fd03f19

**Comment by kuma4649** [comment]
ありがとうございます。
近いうちに調べてみようと思います

**Comment by kuma4649** [comment]
TAG577で修正しました。お試しください。

**Comment by musicalman** [comment]
Ay3のセカンダリが動きました！ありがとうございます。
しかし、C140のセカンダリチップは動作しません。vgmが再生できない。
これは、他のpcmチップでも問題になっています。

**Comment by kuma4649** [comment]
https://user-images.githubusercontent.com/7453752/153546908-7bb49eae-710e-4e46-9955-e447216d5766.mp4

大丈夫みたいですよ？

**Comment by musicalman** [comment]
まだ成功していません。 最新のvgmplayとMDPlayerの両方を試しました。
私のgwiファイルを何か変更しましたか？音が違うような気がするのですが。

**Comment by kuma4649** [comment]
わかりやすいように和音に改造しています。

**Comment by kuma4649** [comment]
壊れているvgmファイルが出力されるようですね。修正します。

**Comment by kuma4649** [comment]
TAG579をお試しください。

**Comment by musicalman** [comment]
動作します。今のところ、問題は見つかりませんでした
