### ISSUE TITLE
Gigatron sound engine support

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#130]
Gigatron is an 8bit computer composed of only 7400 series chips, and it has a 4-channel PSG. At present, I have developed a music engine using C language for Gigatron. If you are interested, I hope you can add Gigatron to the mml2vgm project. I can provide all the required materials, which are legal and open source.
Actually I want to be able to use mml2vgm to convert mml to an array of the gigatron music engine, the so called output function.

**Comment by kuma4649** [comment]
おぉそれは凄いですね！
PSGチップは何なのでしょうか？
デバッグ環境やエミュレーション環境が揃うなら、少し興味がありますw

**Comment by denjhang** [comment]
I have a debug and emulation environment running under Windows 10, and of course Windows 7 works as well.
[gtemuAT67 v1.0.9R.zip](https://github.com/kuma4649/mml2vgm/files/8505674/gtemuAT67.v1.0.9R.zip)
gtemuAT67 is the latest gigatron emulator with complete functions. The compressed package contains the binary compiled by myself, which can be used directly after decompression.

**Comment by denjhang** [comment]
[glcc-1.4.zip](https://github.com/kuma4649/mml2vgm/files/8505691/glcc-1.4.zip)

GLCC is the ported version of LCC in gigatron, which has many giagron unique header files, all located in 
·glcc\lib\gigatron-lcc\include\gigatron·

**Comment by denjhang** [comment]
[gigatron sound engine.zip](https://github.com/kuma4649/mml2vgm/files/8505736/gigatron.sound.engine.zip)
The engine.c in the compressed package is the music engine I wrote using glcc, and it can work normally.
mml2gt_note.xlsx is the pitch table of the gigatron music engine, and the other txt files are my functional description (in Chinese) of the music engine.

**Comment by denjhang** [comment]
[test_envlope.zip](https://github.com/kuma4649/mml2vgm/files/8505762/test_envlope.zip)
Here is an example of the steps I envisioned to convert mml to gigatron music, explained in great detail (in Chinese).

**Comment by denjhang** [comment]
[step22.zip](https://github.com/kuma4649/mml2vgm/files/8505783/step22.zip)
This is an example of the gigaron music engine with music, the source code and the gigatron executable in the zip.You can run it directly in the emulator.

**Comment by denjhang** [comment]
My music engine may not be fully functional, since gigaron audio is even WSG-like, i.e. waveforms can be replaced and samples may be played. Here is the official documentation for gigatron audio.
[Audio.txt](https://github.com/kuma4649/mml2vgm/files/8505802/Audio.txt)

**Comment by denjhang** [comment]
Of course, gigatron can not only use glcc, but also some development languages dedicated to gigatron, such as gtbasic, gcl, vcpu assembly and native assembly. But I don't know much about them.
I think gtbasic and gcl can also implement such a music engine, and gtbasic is much more powerful and efficient than glcc. gcl is a low-level language.

**Comment by denjhang** [comment]
Briefly introduce the audio of gigatron:
4-channel PSG/WSG.
Support pitch and can support pitch bend. Volume adjustment can realize software volume envelope and waveform dynamic switching.
Four built-in waveforms: triangle wave, sawtooth wave, square wave, periodic metal noise.
The built-in waveform is in a specific area in RAM, so it can be replaced.

**Comment by kuma4649** [comment]
gtemuAT67.exeを実行するとフルスクリーンになってしまうのですが、ウィンドウモードはありますか？

**Comment by denjhang** [comment]
You can modify the contents of graphics_config.ini to switch between fullscreen and windowed, as well as modify the display resolution.
`
[Monitor]              ; case sensitive
Fullscreen  = 1        ; windowed = 0, fullscreen = 1
Resizable   = 1        ; disable/enable resizable, only works in windowed mode
Borderless  = 0        ; disable/enable borderless, only works in windowed mode and overrides Resizable
VSync       = 0        ; disable/enable VSync, (not normally of value to enable)
FixedSize   = 0        ; disable/enable monitor independant size, ignores everything except Width and Height
Filter      = 0        ; 0=Nearest, 1=Linear, 2=Best        
Width       = 320      ; Desktop or <value>, only works in windowed mode
Height      = 240      ; Desktop or <value>, only works in windowed mode
ScaleX      = 1.5      ; <value>, only works in windowed mode
ScaleY      = 1.5      ; <value>, only works in windowed mode
PosX        = 40       ; <value>, only works in windowed mode
PosY        = 40       ; <value>, only works in windowed mode

`

**Comment by kuma4649** [comment]
エミュレータのソースコードはありますでしょうか

**Comment by denjhang** [comment]
> エミュレータのソースコードはありますでしょうか

https://github.com/kervinck/gigatron-rom/tree/master/Contrib/at67
The gtemuAT67 emulator source code is located here. I was able to compile it successfully using SDL2 and the latest version of GCC. Of course, you can also use VS2019 and the like to compile.
Of course, other contents in this folder are also important, including the source code of the gtbasic compiler, as well as many gtbasic-based program examples. Since at67 has not organized a more systematic gtbasic description, I have not learned to use it for the time being.

**Comment by denjhang** [comment]
> エミュレータのソースコードはありますでしょうか

https://github.com/kervinck/gigatron-rom/tree/master/Contrib/at67
The gtemuAT67 emulator source code is located here. I was able to compile it successfully using SDL2 and the latest version of GCC. Of course, you can also use VS2019 and the like to compile.
Of course, other contents in this folder are also important, including the source code of the gtbasic compiler, as well as many gtbasic-based program examples. Since at67 has not organized a more systematic gtbasic description, I have not learned to use it for the time being.

**Comment by kuma4649** [comment]
少しソースをよみましたけども、音声処理だけをC#で再現させるのはかなり手間がかかると思います。
ここができないと、MDSoundに追加できなく、mml2vgmでも使用できないです。
何とかなりませんか？

**Comment by denjhang** [comment]
If it is difficult to achieve the original gigatron audio simulation, it can be simplified. I simply understand gigatron as a 4-channel WSG, but the output audio has only 4-bit samples (6-bit or even 8-bit samples can also be achieved by hardware modification). I have a register table of the audio part of gigatron here, you can refer to it to write a C# audio core.

Of course, even though I can't play gigatron audio with MDSound, I'd be more than content to just convert the mml to a gigatron executable.

**Comment by denjhang** [comment]
Sound basics
============

There is a secondary output port (XOUT) with 8 bits. It is split
in 4 bits for the LEDs, and 4 bits that go into a 4-bit DAC resistor
array to form 16 output levels. By default, we have 4 sound channels
in software that are 6 bits each internally. At the beginning of
each scan line, one of these software channels gets updated to
compute a new 6-bits sample. So one software channel update happens
during every horizontal VGA sync pulse. After every 4 scan lines,
the top 4 bits of their sum gets output to the sound part of the
XOUT register.

The 4 software channels can independently generate a tone and a
waveform. Some of the preprogrammed waveforms are triangle, sawtooth,
pulse and something that looks like noise, but sounds a bit metallic.
It can all be changed of course, as it is all software-defined.

Controls
--------

There are 6 bytes for each sound channel. They're at the top of
page 1..4.

       0                                                       255
      +----------------------------------------------------------+
$0000 |                        Zero page                         |
      +------------------------------------+---------+-----------+
$0100 | Video table                        | vReset  | Channel 1 |
      +------------------------------------+---------+-----------+
$0200 |                                              | Channel 2 |
      |                                              +-----------+
$0300 |                                              | Channel 3 |
      |                                              +-----------+
$0400 |            User vCPU code and/or data        | Channel 4 |
      |                                              +-----------+
      |                                                          |

The 6 bytes are:

wavA      Modulation after table lookup with ADD operation and
          optional clipping (can approximate PWM with this)
wavX      Modulation of index with XOR operation
keyL:keyH 15-bit frequency (bit7 of keyL should be 0).
          There is a lookup table on page 7 in ROM
oscL:oscH 15-bit phase, automatically incremented with keyL:keyH
          every 4 scan lines (1 channel per scan line).

(You typically don't write into oscL,oscH)

The sound synthesises runs during every horizontal pulse of the VGA
signal. It is implemented twice, once for visible lines and once
for vertical blank. The sample update runs in the videoC lines, or
their equivalents in vBlank. A video frame has 521 lines, so there
is no fixed mapping from video line to channel.

    In pseudo code:
    ----------------------------------------------------------------
    For every channel:
      "osc" += "key"                // Advance phase
      byte i = oscH & 0xfc          // Keep only the highest 6 bits
           i ^= wavX                // Low 2 bits select waveform.
                                    // High 6 bits give effects.
           i = soundTable[i] + wavA // More sound effect options
           i = i&128 ? 63 : i&63
      sample += i

    Every 4 scan lines:
      1. Emit sample & 0xf0         // The DAC has 4-bits
      2. Reset sample
           sample = 3               // Why 3? Any value <=3 (=255-4*63) will
                                    // work, and we have only 1 cycle available
           st $03,[$03]             // for this, so operand is address and value
    ----------------------------------------------------------------

Notes
-----

The ROM has a handy lookup table for the frequencies that is
calculated for a 6.25 MHz system doing 200 cycles per horizontal
sync.

Note: index 0 = 0 Hz = OFF

    ROM table at $0900
    ----------------------------------------------------------------
    notesTable:   0900 0000  ld   $00
                  0901 0000  ld   $00
                  0902 0045  ld   $45         ;C-0 (16.4 Hz)
                  0903 0000  ld   $00
                  0904 0049  ld   $49         ;C#0 (17.3 Hz)
                  0905 0000  ld   $00
    [...]
                  09be 001a  ld   $1a         ;A#7 (3729.3 Hz)
                  09bf 007a  ld   $7a
    ----------------------------------------------------------------

The waveforms are stored in RAM page 7. They are initialised once
at boot time and then never again (so not with soft reset). [Edit:
from ROM v4 onwards, these are reinitialised with each soft reset!]
You select one with the low two bits of wavX. They look like below.
The page is initialised as noise (0), triangle (1), pulse (2) and
sawtooth (3). You can change them, but then the next application
will see your changes. You shouldn't change the sawtooth waveform
(3) because it doubles as a right-shift-2 lookup table for the
SYS_Unpack_56 function used by Pictures.

Image: https://forum.gigatron.io/download/file.php?id=8

**Comment by kuma4649** [comment]
pseudo Codeだと詳細がわからないのですが、それに該当する実際のコードはどこにありますでしょうか

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1516903532431286272?s=20&t=b8IqlU_ApMxgPlml_BdICA

**Comment by kuma4649** [comment]
こんな感じでよいのかしら？

**Comment by denjhang** [comment]
> こんな感じでよいのかしら？

Probably so, actually I don't know the underlying principles very well.

**Comment by denjhang** [comment]
`#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

typedef struct { // TTL state that the CPU controls
  uint16_t PC;
  uint8_t IR, D, AC, X, Y, OUT, undef;
} CpuState;

uint8_t ROM[1<<16][2], RAM[1<<15], IN=0xff;

CpuState cpuCycle(const CpuState S)
{
  CpuState T = S; // New state is old state unless something changes

  T.IR = ROM[S.PC][0]; // Instruction Fetch
  T.D  = ROM[S.PC][1];

  int ins = S.IR >> 5;       // Instruction
  int mod = (S.IR >> 2) & 7; // Addressing mode (or condition)
  int bus = S.IR&3;          // Busmode
  int W = (ins == 6);        // Write instruction?
  int J = (ins == 7);        // Jump instruction?

  uint8_t lo=S.D, hi=0, *to=NULL; // Mode Decoder
  int incX=0;
  if (!J)
    switch (mod) {
      #define E(p) (W?0:p) // Disable AC and OUT loading during RAM write
      case 0: to=E(&T.AC);                          break;
      case 1: to=E(&T.AC); lo=S.X;                  break;
      case 2: to=E(&T.AC);         hi=S.Y;          break;
      case 3: to=E(&T.AC); lo=S.X; hi=S.Y;          break;
      case 4: to=  &T.X;                            break;
      case 5: to=  &T.Y;                            break;
      case 6: to=E(&T.OUT);                         break;
      case 7: to=E(&T.OUT); lo=S.X; hi=S.Y; incX=1; break;
    }
  uint16_t addr = (hi << 8) | lo;

  int B = S.undef; // Data Bus
  switch (bus) {
    case 0: B=S.D;                        break;
    case 1: if (!W) B = RAM[addr&0x7fff]; break;
    case 2: B=S.AC;                       break;
    case 3: B=IN;                         break;
  }

  if (W) RAM[addr&0x7fff] = B; // Random Access Memory

  uint8_t ALU; // Arithmetic and Logic Unit
  switch (ins) {
    case 0: ALU =        B; break; // LD
    case 1: ALU = S.AC & B; break; // ANDA
    case 2: ALU = S.AC | B; break; // ORA
    case 3: ALU = S.AC ^ B; break; // XORA
    case 4: ALU = S.AC + B; break; // ADDA
    case 5: ALU = S.AC - B; break; // SUBA
    case 6: ALU = S.AC;     break; // ST
    case 7: ALU = -S.AC;    break; // Bcc/JMP
  }

  if (to) *to = ALU; // Load value into register
  if (incX) T.X = S.X + 1; // Increment X

  T.PC = S.PC + 1; // Next instruction
  if (J) {
    if (mod != 0) { // Conditional branch within page
      int cond = (S.AC>>7) + 2*(S.AC==0);
      if (mod & (1 << cond)) // 74153
        T.PC = (S.PC & 0xff00) | B;
    } else
      T.PC = (S.Y << 8) | B; // Unconditional far jump
  }
  return T;
}

void garble(uint8_t mem[], int len)
{
  for (int i=0; i<len; i++) mem[i] = rand();
}

int main(int argc, char *argv[])
{
  CpuState S;
  srand(time(NULL)); // Initialize with randomized data
  garble((void*)ROM, sizeof ROM);
  garble((void*)RAM, sizeof RAM);
  garble((void*)&S, sizeof S);

  FILE *fp = fopen(argc>1 ? argv[1] : "gigatron.rom", "rb");
  if (!fp) {
    fprintf(stderr, "Error: failed to open ROM file\n");
    exit(EXIT_FAILURE);
  }
  fread(ROM, 1, sizeof ROM, fp);
  fclose(fp);

  int vgaX=0, vgaY=0;
  for (long long t=-2; ; t++) {
    if (t < 0) S.PC = 0; // MCP100 Power-On Reset

    CpuState T = cpuCycle(S); // Update CPU

    int hSync = (T.OUT & 0x40) - (S.OUT & 0x40); // "VGA monitor" (use simple stdout)
    int vSync = (T.OUT & 0x80) - (S.OUT & 0x80);
    if (vSync < 0) vgaY = -36; // Falling vSync edge
    if (vgaX++ < 200) {
      if (hSync) putchar('|');              // Visual indicator of hSync
      else if (vgaX == 200) putchar('>');   // Too many pixels
      else if (~S.OUT & 0x80) putchar('^'); // Visualize vBlank pulse
      else putchar(32 + (S.OUT & 63));      // Plot pixel
    }
    if (hSync > 0) { // Rising hSync edge
      printf("%s line %-3d xout %02x t %0.3f\n",
             vgaX!=200 ? "~" : "", // Mark horizontal cycle errors
             vgaY, T.AC, t/6.250e+06);
      vgaX = 0;
      vgaY++;
      T.undef = rand() & 0xff; // Change this once in a while
    }
    S=T;
  }
  return 0;
}
`

**Comment by kuma4649** [comment]
>gtemu.zip
私が欲しいものとは違うかな...

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1517112906747641857?s=20&t=UXiZexo8FmzdKQQ7c6b7Iw

**Comment by denjhang** [comment]
I simply think that wavA can adjust the volume, when wavA is between 64 and 127 can adjust the volume.
wavX is the selection waveform, the range is 0 to 3.
keyH and keyL together control the pitch.
I don't change oscH and oscL. So I don't know these two either.

**Comment by denjhang** [comment]
Ok, so how is it going now, with the video you uploaded, I don't think there's anything wrong with it.

**Comment by kuma4649** [comment]
進捗無しです(^^;

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1520747897821986817?s=20&t=uGiuGBLYbi66yYG-QJXfQA

**Comment by denjhang** [comment]
I think it should be released.
