### ISSUE TITLE
トーンダブラーがコンパイル通らなくなってる

### ISSUE THREAD

**Issue by maro-suzuki** [kuma4649/mml2vgm#131]
TAG592でトーンダブラーを使うと、

MML文法解析
型 'System.Collections.Generic.List`1[Core.MML]' のオブジェクトを型 'Core.Note' にキャストできません。

とエラーが出ます。
過去作のTD使用gwiでも同様のエラーが出るようになってました。

TAG560では通りました。TAG566ではダメだったのでこの間かと思います。
IDEじゃない方を使用しています。

**Comment by kuma4649** [comment]
おはようございます！くまです。

ありがとうございます。後で調査してみます。
しばらくつ勝手なかった機能だからなんかありそう。。。

よろしくお願いします。

----- Original Message -----
>Date: Thu, 16 Jun 2022 18:09:43 -0700
>From: maro-suzuki ***@***.***>
>To: kuma4649/mml2vgm ***@***.***>
>Cc: Subscribed ***@***.***>
>Subject: [kuma4649/mml2vgm] トーンダブラーがコンパイル通らなくなってる (Issue
 #131)
>
>
>TAG592でトーンダブラーを使うと、
>
>MML文法解析
>型 'System.Collections.Generic.List`1[Core.MML]' のオブジェクトを型 'Core.Not
e' にキャストできません。

**Comment by kuma4649** [comment]
こっちでしたか！
