### ISSUE TITLE
Latest version not running (English Only?)

### ISSUE THREAD

**Issue by pedipanol** [kuma4649/mml2vgm#132]
I'm getting these 2 errors when trying to run the latest version of the program.
```
致命的なエラー
Some or all identity references could not be translated.
```
```
致命的なエラー
Object reference not set to an instance of an object.
```

Clicking OK on the first error closes the error window and launches the program.
Then the second error appears and the program can't be used.

An old version I had before (TAG530) still works fine. I tried running removeZoneIdent.bat but it didn't affect it.

**Comment by kuma4649** [comment]
すみません、
「どのバージョンから発生するようになったか」
と
「エラー画面が欲しいです」
を要求してよろしいでしょうか。

**Comment by pedipanol** [comment]
予めにあまりテスト出来なくてすみません。
TAG547から発生しています。MDPlayerに関しているかしら...

エラー画面はこれです
![image](https://user-images.githubusercontent.com/26771164/193709214-517a5634-e652-4dda-b0cf-fc68e85cd29c.png)
OKするとこれになります
![image](https://user-images.githubusercontent.com/26771164/193709296-3ac4d023-fd2b-493f-ae62-d670d6d1b5cf.png)

**Comment by kuma4649** [comment]
原因、多分分かりました。
共有メモリが使えなくてエラーが出ていると思われます。。。

直ぐには直せませんが、共有メモリを使用するのをやめようと思います。。。

**Comment by kuma4649** [comment]
TAG651を用意しました。お試しください。

**Comment by pedipanol** [comment]
成功でした、ありがとうございました！
