### ISSUE TITLE
How to change YM chip for MUC file ? (to be Sega Genesis Accurate)

### ISSUE THREAD

**Issue by NewNova88** [kuma4649/mml2vgm#137]
Hello there.
I was wondering how to change the YM chip used.
By default, it's the YM2608, but I want the YM2612, the same as the Sega Genesis one.
(I know I have to get rid of ADPCM for that)
Is there a way ? Maybe in the settings ? Or directly in the MUC file ?

Thanks in advance !

![MUC](https://user-images.githubusercontent.com/55078083/234126590-5ac044f2-f831-4167-9c31-204087e4a10b.png)

**Comment by kuma4649** [comment]
mucomMD2vgmをお勧めします♪
