### ISSUE TITLE
XGM FMモードのE06でベンドコマンドが効かない

### ISSUE THREAD

**Issue by maro-suzuki** [kuma4649/mml2vgm#139]
FMモードでのE06で、ベンドコマンド'_'が効きません

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/mml2vgm/assets/7453752/8e47f29f-401f-4562-934e-6d72f130576c)
現象確認しました。対応させていただきます。

**Comment by kuma4649** [comment]
TAG698で修正しました。ご確認ください。

**Comment by maro-suzuki** [comment]
確認しました。
ありがとうございます。
