### ISSUE TITLE
mono環境でのパス表記について

### ISSUE THREAD

**Issue by erio2018** [kuma4649/mml2vgm#14]
mono環境(Debian)でmvc.exeでのコンパイル時に、サブディレクトリ配下のwav等が参照できません。
パスの表記を"\\"ではなく、"/"にすると読み込めますので、"/"でもサーチするように修正して頂きたいです。

例：sample\test.gwi
読み込めない
`
'@ P 1,"wav\Guitar.wav", 8000, 100, C140, 1400
`

読み込める
`
'@ P 1,"wav/Guitar.wav", 8000, 100, C140, 1400
`

**Comment by kuma4649** [comment]
こちらも併せて検討させていただきます～

**Comment by kuma4649** [comment]
修正完了しました。
Debianでの動作確認とご報告を是非お願いします！

**Comment by erio2018** [comment]
Windows上のWSL/Debian環境と、Android上のLinuxDeploy/Debian環境という少し特殊な環境ですが、
両方ともmvc.exeでスラッシュ、バックスラッシュ表記で問題無く相対パスで問題無くwavファイルの読み込みが出来るのを確認しました。
Windows上のDos窓環境でもスラッシュ、バックスラッシュ表記両方ともOKでした。

素早い対応ありがとうございました！！

**Comment by kuma4649** [comment]
ご報告ありがとうございます。
無事動いたということで安心しました！

これからもよろしくお願いします。
