### ISSUE TITLE
TLオフセットコマンドの補正値がおかしくなる

### ISSUE THREAD

**Issue by maro-suzuki** [kuma4649/mml2vgm#140]
複数の定義mapを使うと、補正値が狂います。
ひとつの定義mapだけでも、間にOFを挟むと（TLOFSON 2,1  ~  TLOFSOF  ~  TLOFSON 2,1）補正値がおかしくなります。

また、FMモードのE06ではTLオフセットコマンドが弾かれます。

サンプルgwiをメールしましたので、ご確認お願い致します。

**Comment by kuma4649** [comment]
後で確認します

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/mml2vgm/assets/7453752/d9eb651c-f638-4305-aff9-a0b694eb9602)
確認しましたので修正します。
上の図のように演奏するようになります。

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/mml2vgm/assets/7453752/2cf6046f-d1ac-4878-a4f0-0cf3e678d0db)
確認しましたので修正します。
上の図のように演奏するようになる予定ですので注意お願いします。

**Comment by kuma4649** [comment]
TAG698で修正しました。ご確認ください。

**Comment by maro-suzuki** [comment]
ご対応ありがとうございます。

TLOFSON2,1
TLOFSOF2
TLOFSON3,1

のように定義mapを切り替えた場合、"TLOFSOF2"の有無で"TLOFSON3,1"の補正値が変わってしまいます。
（TLOFSOF2有りの補正値は正しい）
これはOF必須の仕様と思えば良いですか？

サンプルが必要なら、メールしたgwiをご確認ください。

**Comment by kuma4649** [comment]
TLOFSON3,1の直後の発音した時点で
2の効果が残っているのであればバグなのですがどんな感じですか？

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/mml2vgm/assets/7453752/cae096c4-90f3-4e0d-b8ff-cefe5df04427)
↑大丈夫そうなんですけども...

**Comment by maro-suzuki** [comment]
複数の音階を鳴らしてみてもらえませんか？

改めて"TLOFS訂正.gwi"をメールしました。
mml中にTLの変化値も書いてあるので、確認してみてください。

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/mml2vgm/assets/7453752/bf60e7b3-679a-4c54-8a36-ba6fcfcae5a9)
問題なさそうです...

**Comment by kuma4649** [comment]
あ、TLOFSは複数重ねることができます...

**Comment by maro-suzuki** [comment]
あー、2つのmapを重ねた値だったんですね。
了解です。
では切り替えるならTLOFSOF必須という事で。

ありがとうございました。
