### ISSUE TITLE
Can't transpose down (error code:1)

### ISSUE THREAD

**Issue by Zenobian** [kuma4649/mml2vgm#141]
I have an issue, probably I just don't understand how PMD works
I can't transpose my track down with #Transpose command, it gives me an error (see screensot)
But without "-" everything actually works perfectly fine and track is transposed by 6 semitones up
What should I do?

初心者なのでなにかを見落としただけかもしれませんがPMDコマンドでエラー発生
コマンド#Transposeで曲を移調できるのは上だけです
"-"を入れるとスクショの通りコンパイラエラーerror code:1発生します
エンコードの問題かと思ったんですがそれらしい設定見つけられませんでした
PMD公式マニュアルでは普通にマイナスを入れれば半音単位で下げられると書いてありますので途方に暮れてます
![Без имени](https://github.com/kuma4649/mml2vgm/assets/10101810/fbd37a2e-0424-4c7a-a481-d22130a0056d)

**Comment by kuma4649** [comment]
これは、mml2vgmIDE上のみで発生する現象でしょうか？
或いは本来のPMD上でも発生する現象でしょうか？

**Comment by kuma4649** [comment]
オリジナルのほうで対応いただけましたので、PMDDotNETでも対応させていただきました！
お試しください。

**Comment by Zenobian** [comment]
確かに下げられるようになりました！
対応ありがとうございました！
