### ISSUE TITLE
vコマンドをエイリアスにすると、yTLコマンドが正常に動作しない

### ISSUE THREAD

**Issue by maro-suzuki** [kuma4649/mml2vgm#142]
下記のようにエイリアス%v127を使用すると、以降のyTLコマンドがslot2,4に効きません。
(slot1,3には効く。y$n,127でも同様)

// 音色は適当
'@ N 013
   AR  DR  SR  RR  SL  TL  KS  ML  DT  AM  SSG-EG
'@ 020,024,000,005,000,026,000,004,000,000,000
'@ 025,024,000,005,000,026,000,004,000,000,000
'@ 020,024,000,005,000,026,000,004,003,000,000
'@ 025,024,000,005,000,026,000,004,003,000,000
   ALG FB
'@ 004,000

'%v127 v119

'E02 @13 %v127
'E02 yTL,4,127 o4e1

**Comment by kuma4649** [comment]
しらべまーす

**Comment by kuma4649** [comment]
発音時（この場合はe1)に音量を設定しなおすから、yTLで送信した値は上書きされてしまうようです。
この動作は他の数多くのコマンドによる音量操作を実現するためのものであるため
安易に取り去ることはできません。
よって仕様です。。。。


と言いたいところですが、yコマンドで音量操作をしたいケースもあるだろうなとは思いますので、

音量操作を抑制、再開するコマンドをそれぞれ新たに追加して
抑制中はyコマンド以外ではTLに数値を送らないようにできるようにしようと思います

**Comment by kuma4649** [comment]
TAG708にて対応

**Comment by kuma4649** [comment]
https://x.com/kumakumakumaT_T/status/1722212187396300965?s=20
