### ISSUE TITLE
mml command table is out of date

### ISSUE THREAD

**Issue by ultrasound1372** [kuma4649/mml2vgm#143]
The file `mmlCommandTable.md` was last modified on June 19, 2022, however more commands and variations have been added since then. These variations are documented in the command memo, but not in the table. As a blind user I rely on the format of the command table, as I cannot distinguish supported chips with the scheme used in the memo.

----------

ファイル`mmlCommandTable.md`の最終更新日は2022年6月19日だが、それ以降にコマンドやバリエーションが追加されている。これらのバリエーションはコマンドメモに記載されているが、表には記載されていない。目の不自由なユーザーとしては、メモで使われているスキームではサポートされているチップを区別することができないので、コマンドテーブルのフォーマットに頼っている。

**Comment by kuma4649** [comment]
TAG709で対応しました
