### ISSUE TITLE
mvc.exeでの曲情報定義内パート名定義エラーについて

### ISSUE THREAD

**Issue by erio2018** [kuma4649/mml2vgm#15]
mvc.exeで test\T0000_SongInfoDef.gwi のコンパイル時に以下のエラーが出ます。

`Error : (F:T0000_SongInfoDef.gwi L:68)エンベロープ定義に指定された音色番号(110)が存在しません。`

15行目からのパート設定をまるっと削除して、MML部を'F1～に変更するとエラー無くコンパイル出来たので、パート設定部に問題があると思われます。
修正対応お願いします。

**Comment by kuma4649** [comment]
ありがとうございます！
確認しまっす

**Comment by kuma4649** [comment]
修正完了しました。ご確認ください。
こちらはクローズさせていただきます。

**Comment by erio2018** [comment]
コンパイル時にエラーが出ずに正常にコンパイル出来ることを確認しました。
対応ありがとうございました！
