### ISSUE TITLE
コマンドライン版(mvc.exe)の戻り値について

### ISSUE THREAD

**Issue by erio2018** [kuma4649/mml2vgm#16]
要望です。

vimから利用させてもらっていますが、エラー時にコマンドの戻り値を元に処理を分岐させたいです。
正常時は0が返ってくるようですが、エラー時に0以外が返ってくるような変更は可能でしょうか。

よろしくお願いします。

**Comment by kuma4649** [comment]
vimで受け取れるかどうかまでは試せませんでしたが、コマンドプロンプトのエラーレベルにて値が取得できることを確認しました。
是非、レポートいただけると嬉しいです！

**Comment by erio2018** [comment]
vimでエラーキャッチ出来ました！スクリーンショットの右下がエラー出力先です。
しかし、寝て起きたら対応済みとか対応早すぎですｗ
<img src="https://user-images.githubusercontent.com/35863829/58193192-6a176900-7cfd-11e9-8d8f-6336eb747bbb.png" width="520px">

コマンドでもエラーコードがちゃんと返ってきてるのを確認しました。
<img src="https://user-images.githubusercontent.com/35863829/58192515-ddb87680-7cfb-11e9-8079-4e2e5acc96c0.png" width="120px">

ただ、エラー行が1行少ない値が出てる？
もう少し検証して隙あらばソース確認させて頂いてからまたIssue上げさせて貰います。

対応ありがとうございました。

**Comment by kuma4649** [comment]
ご報告ありがとうございます！
問題無いようでひと安心です。
vimの画面カッコいいっすなぁ
IDEでやってる事一通り出来そう…

必要であればエラーとワーニングのメッセージを標準エラー出力に出すようにしますがいかがでしょう

あとトレース情報付きの演奏データ出力とか…

**Comment by kuma4649** [comment]
あ エラー行数が1行ずれてるのは
多分0はじまりだからです…
IDE向けに調整してしまっています
直しましょうか？

**Comment by erio2018** [comment]
IDE用に0オリジンなんですね。
mvc.exeの出力時にだけでも1オリジンで出力していただけると助かります。

> IDEでやってる事一通り出来そう…
いや、あの演奏トレースは流石に厳しいかと…。
既存のMML表示させてトレース演奏させてるだけでカッコイイですよね。
母艦のWindowsでMDPlayer共々使わせて貰ってます。
スニペットとかはplugin任せでゴリゴリ出来るでしょうが、環境がスマフォベースなので
あまり載せすぎると重くなるのが難点なんです。

> 必要であればエラーとワーニングのメッセージを標準エラー出力に出すようにしますがいかがでしょう
あ、これは良いですね。
今のところ有効な使いみちが思い浮かばないですが、メッセージの意味別で出力先が予め
分かれていてもらえると何かと後処理しやすいように思います。

> あとトレース情報付きの演奏データ出力とか…
これは技術的には凄く興味ありますけど、使いこなせないと言い切れますｗ
それほど手間でなければお願いしたいですが…

エラー行と出力先、手間でなければ演奏データ出力でお願いします！
あ、実際にコンパイルせずにCountだけ出力するモードも出来たら失礼ついでに要望させてください！

**Comment by kuma4649** [comment]
＞母艦のWindowsでMDPlayer共々使わせて貰ってます。
ありがとうございますーTvT

＞環境がスマフォベース
うぇぇぇ～す、すごい時代じゃのぅ…

＞分かれていて
エラーメッセージ選択すると該当行に飛ぶようにするときなどに
最初からエラーだけ分かれてたほうが処理しやすいかなと思います。

＞トレース情報、大盛り。
これはIDEのほうで必須になりそうなので実装予定です。なんとなくの思いつきですｗ

＞エラー行と出力先、手間でなければ演奏データ出力でお願いします！
＞あ、実際にコンパイルせずにCountだけ出力するモードも
ご要望ありがとうございます！ありがたく対応させていただきます！

**Comment by kuma4649** [comment]
というわけで、TAG057にてmvcの修正を行いました。
ご確認ください。

**Comment by erio2018** [comment]
相変わらず対応早くて素晴らしいです。
幾つか確認しました。

<img src="https://user-images.githubusercontent.com/35863829/58294477-44758700-7e05-11e9-8bf1-3d608842bdac.png" width="480px">

○標準エラーへの出力、問題なく出力されてるのを確認しました。
○中身はわからないですが、トレースも出力確認できました。
✕フルパスでファイル指定するとオプションの解析に失敗してエラーコードも0が返ってきます。
 　(~はホームディレクトリ、ここでは/home/erioに展開されます)
✕ファイル名の後ろにオプション書いちゃうと、例外発生ちゃいます。
　(これは前の版からあったかもしれません)

**Comment by kuma4649** [comment]
レポートありがとうございます。
フルパス〜
の件はオプション指定のはじめの文字がーのほかに/も見るようにしてしまっているからです。

あとファイル名の後にオプションは置けない仕様になってます…にしても例外バーンは
ちょっとアレなのでチェックするようにします…家帰ったらw

**Comment by kuma4649** [comment]
・オプションは-で始まるもののみとする。
・ファイル指定の後にオプションを指定することはできない。
　（もし指定するとオプションの文字をファイル名として扱う。
　あえてエラーとはしない。）

このような対応になります

**Comment by erio2018** [comment]
フルパス指定でのコンパイル確認できました！
オプション後ろにして実行したらしれっと -v- なんてファイルが出来てて笑いましたｗ
先頭ハイフンのファイルって消すのに戸惑うんです。。。
でも、Exception吐かなくなったのでスッキリです。

対応ありがとうございました！

**Comment by kuma4649** [comment]
動作したようですね。
・出力先となるファイル名は省略することができる
・-で始まるファイルを作成することがOS的に可能である。
という優先したい条件があるので
オプションのファイル名で作れてしまうのはまぁ仕様で良いかなと考えてます。。。(^^;

また何かありましたらよろしくお願いします！
