### ISSUE TITLE
オフライン環境で入力支援機能がエラーを返す

### ISSUE THREAD

**Issue by sdhizumi** [kuma4649/mml2vgm#17]
![mmk2vgm_error](https://user-images.githubusercontent.com/31327231/58305380-d3e55f00-7e32-11e9-90ba-c6eafc222259.jpg)
オフライン環境でTAG057版を使用していた所、入力支援機能が立ち上がった際に上画像のようにエラーが発生してしまいます。
入力支援機能で参照しているvalsound様への接続が完了しないエラーと思われますので、例えば
・入力支援機能を立ち上げた時点ではvalsound様を参照せずに、該当項目を選択した時点で接続を試行→アクセス可能な場合は現状と同じようにパッチを参照し、アクセスできない状況の場合はアラートを出す
といった挙動であれば両立できるのではないかと思います。
ご検討宜しくお願い致します。

**Comment by kuma4649** [comment]
レポートありがとうございます。
確かにおっしゃる通りです。

対応内容
・接続に失敗したら
　①エラーを表示する。
　②以降オフラインモードに移行するかユーザーに問い合わせる。
　（永続的に。又は今回の動作のみ。或いは再接続にチャレンジを選択できるようにする)
・設定画面にオフラインモードのチェックボックスを用意する。

こんな感じにしようと思います。

**Comment by kuma4649** [comment]
TAG059にて対応しましたぁ。多分これで大丈夫だと思います。
永続的なオフラインモードは設定画面で設定もできます。
