### ISSUE TITLE
C140 loop point bug?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#18]
I cannot speak Japanese, so I'm using Google Translate to provide Japanese text if it helps.
I am trying to use the c140 chip in mml2vgm, but I believe I have found a bug. I am having problems inserting the loop points into the samples.
When I play the first sample, everything sounds the way it should. But when I play the second sample, the first sample is included in the loop. I have not managed to find a way to get the second sample to loop correctly. I haven't tried adding more samples.
I'm very new to mml2vgm though, so I might be doing something wrong. I've attached a zip file that shows what I'm doing, if it would help figure out what's going on.
If you could help me, it would be greatly appreciated. Thank you so much and have a great day!

私は日本語が話せないので、日本語のテキストを提供するためにGoogle Translateを使っています。
mml2vgmでc140チップを使用しようとしていますが、バグが見つかったと思います。サンプルにループポイントを挿入するのに問題があります。
私が最初のサンプルを演奏するとき、すべてはそれがあるべきように聞こえます。しかし、2番目のサンプルを演奏すると、最初のサンプルがループに含まれています。 2番目のサンプルを正しくループさせる方法を見つけることができませんでした。もっとサンプルを追加してみませんでした。
私はmml2vgmに非常に新しいです、それで私は何かが悪いことをしているかもしれません。何が起こっているのか理解するのに役立つなら、私は自分のしていることを示すzipファイルを添付しました。
あなたが私を助けることができれば、それは大歓迎です。どうもありがとうございました、素晴らしい一日を！

**Comment by musicalman** [comment]
Forgot to attach zip

**Comment by kuma4649** [comment]
こんにちは！ご報告ありがとうございます！
添付があるとのことですが、zipファイルはどこからいただけますでしょうか？

**Comment by musicalman** [comment]
I'm not sure if the file was attached, so here is a link to it:
ファイルが添付されているかどうかはわかりません。そのため、ここにリンクがあります。
http://www.fileconvoy.com/gf.php?id=g599b45cb41a064f01000175034.12865865c0ab51b07973fa0&sts=1559962495174556621114695485266047d6d684ea1a75443c97

**Comment by kuma4649** [comment]
ありがとうございます。確認しました。

ループポイントの設定バグのようです。
調査後、修正させていただきます！

**Comment by kuma4649** [comment]
修正完了しました！
ご確認くださいませ。

**Comment by musicalman** [comment]
私は4つまでのサンプルを使用しようとしました、そして、すべてはこれまでに正しく働いています。迅速な対応ありがとうございました。
他に問題が見つかった場合、それらを報告するのにGithubを使用する必要がありますか、それとも別の方法でお問い合わせください。私はこのようなことをしないことが多いので、よくわかりません。

**Comment by kuma4649** [comment]
直ったようですね。
よかった！
また何かありましたら、お気軽にお問い合わせください。
今後もよろしくお願いします！
