### ISSUE TITLE
bugs with provisional QSound and K053260 support

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#19]
こんにちは、
これはQSoundについてです。 QSoundのサポートは数日前に追加されただけで、暫定的なものであるため、問題が予想されます。
QSoundを使用すると、3つの問題が発生します。
1. PCMトーン定義の再生レートが誤って解釈されます。数値を大きくすると、ピッチが低くなります。
2.ループポイントの計算が間違っているようです。サンプルの開始からではなく、サンプルの終了から測定されます。
3. C140ループポイントのバグはQSoundにあります。詳細については、https：//github.com/kuma4649/mml2vgm/issues/18を参照してください
必要に応じて、QSoundバグを示すファイルを作成します。
また、K053260は非常に不安定です。私がそれをテストしようとすると、出力ファイルがVGMプラグインでWinampをクラッシュさせることがあります。ほとんどの場合、ノートは正しく再生されませんでした。何が起こっているのか本当に分からないので、何が起こるのか待って見ます。
読んでくれて、このクールなプログラムを開発し続けてくれてありがとう！

**Comment by kuma4649** [comment]
レポートありがとうございます！
早速調査します

**Comment by kuma4649** [comment]
QSound LoopPointについて
 どうやらQSoundのLoopAddressはEnd Addressから引いたものになるようです。
 このままでは使いにくいのでC140と同じ感覚で使えるように修正します。

**Comment by kuma4649** [comment]
というわけで、
TAG101
にて修正版を公開しました。
ご確認お願いします

**Comment by musicalman** [comment]
すべてが正しく機能しているようです。私のレポートを迅速に調査してくれてありがとう！

**Comment by kuma4649** [comment]
これからもよろしくお願いします！
