### ISSUE TITLE
tried to compile with Mono’s xbuild

### ISSUE THREAD

**Issue by nitrofurano** [kuma4649/mml2vgm#2]
what i got was this:
`
guest@macbookair:~/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm$ xbuild /p:Configuration=Release mml2vgm.csproj 
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 6/27/2017 9:00:11 AM.
__________________________________________________
Project "/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/mml2vgm.csproj" (default target(s)):
	Target PrepareForBuild:
		Configuration: Release Platform: AnyCPU
		Created directory "bin/Release/"
		Created directory "obj/Release/"
	Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Windows.Forms' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.5/, assembly named 'System.Windows.Forms' not found.
		For searchpath {PkgConfig}
		Considered System.Windows.Forms, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered System.Windows.Forms, but could not find in the GAC.
		For searchpath {RawFileName}
		Considered 'System.Windows.Forms' as a file, but the file does not exist
		For searchpath bin/Release/
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Windows.Forms' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Windows.Forms.exe' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Windows.Forms.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Data.DataSetExtensions' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.5/, assembly named 'System.Data.DataSetExtensions' not found.
		For searchpath {PkgConfig}
		Considered System.Data.DataSetExtensions, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered System.Data.DataSetExtensions, but could not find in the GAC.
		For searchpath {RawFileName}
		Considered 'System.Data.DataSetExtensions' as a file, but the file does not exist
		For searchpath bin/Release/
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Data.DataSetExtensions' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Data.DataSetExtensions.exe' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Data.DataSetExtensions.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.5/, assembly named 'Microsoft.CSharp' not found.
		For searchpath {PkgConfig}
		Considered Microsoft.CSharp, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered Microsoft.CSharp, but could not find in the GAC.
		For searchpath {RawFileName}
		Considered 'Microsoft.CSharp' as a file, but the file does not exist
		For searchpath bin/Release/
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/Microsoft.CSharp' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/Microsoft.CSharp.exe' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/Microsoft.CSharp.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Net.Http' not resolved
		For searchpath {CandidateAssemblyFiles}
		Warning: {CandidateAssemblyFiles} not supported currently
		For searchpath {HintPathFromItem}
		HintPath attribute not found
		For searchpath {TargetFrameworkDirectory}
		Considered target framework dir /usr/lib/mono/4.5/, assembly named 'System.Net.Http' not found.
		For searchpath {PkgConfig}
		Considered System.Net.Http, but could not find in any pkg-config files.
		For searchpath {GAC}
		Considered System.Net.Http, but could not find in the GAC.
		For searchpath {RawFileName}
		Considered 'System.Net.Http' as a file, but the file does not exist
		For searchpath bin/Release/
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Net.Http' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Net.Http.exe' as a file, but the file does not exist
		Considered '/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/bin/Release/System.Net.Http.dll' as a file, but the file does not exist
Done building project "/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/mml2vgm.csproj".-- FAILED

Build FAILED.

Warnings:

/home/guest/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm/mml2vgm.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Windows.Forms' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Data.DataSetExtensions' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Net.Http' not resolved

	 4 Warning(s)
	 0 Error(s)

Time Elapsed 00:00:01.0005440
guest@macbookair:~/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
guest@macbookair:~/Downloads/mml/mml2vgm-master/mml2vgm/mml2vgm$ 

`

**Comment by kuma4649** [comment]
#1に集約します。
