### ISSUE TITLE
[表示(V)]メニューにて、歌詞ウインドウを[X]で閉じた際にチェックが消えない。

### ISSUE THREAD

**Issue by sdhizumi** [kuma4649/mml2vgm#20]
・[表示(V)]メニューにて、歌詞ウインドウを[X]で閉じた際にチェックが消えない。
歌詞ウインドウをウィンドウ左上の[X]ボタンで閉じた後、[表示(V)]メニューを参照すると表示オンのチェックが消えていません。
(この状態から[表示(V)]メニュー上の[歌詞]をクリックすると、歌詞ウインドウが表示されます。)
画像を添付いたします。
![image](https://user-images.githubusercontent.com/31327231/63360965-41f5df80-c3aa-11e9-9f71-fd8c0f2fe3f7.png)

**Comment by kuma4649** [comment]
レポートありがとうございます！(TvT
現象、理解しました。
原因を探し、次のリリースで修正版を出そうと思います。。。

**Comment by kuma4649** [comment]
この件、修正完了しました。ご確認ください。

**Comment by sdhizumi** [comment]
確認できました。修正ありがとうございます！

**Comment by kuma4649** [comment]
ではこちらは閉じますね♪
