### ISSUE TITLE
TAG103 bugs

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#22]
C140を使用するとエラーが発生するようです。付属のテストc140.gwiはこれを示しています。
コンパイルが成功すると、mml2vgm guiはしばしば閉じます。これは、古いバージョンではそれほど発生しなかったようです。
QSoundで使用できるサンプルデータは65536バイトのみです。現時点では、銀行の切り替えが適切に機能していないと思います。 TAG102でこれを観察しましたが、時間内に報告できませんでした。

**Comment by kuma4649** [comment]
qsoundで１つのサンプルで扱える最大のサイズは65536なのですが
バンクが切り替わらないのは バグです…
修正します。

**Comment by kuma4649** [comment]
C140のコンパイル不良、
QSoundのBank指定不良の修正が完了しました。ご確認ください。

**Comment by musicalman** [comment]
QSoundバンクの切り替えは修正されたようです。
C140は再び機能します。警告が出ているようですが、これまでのところすべてが機能しています。

**Comment by kuma4649** [comment]
>警告が出ている
こちらも教えていただけますでしょうか？
ご面倒をおかけしてごめんなさい。

**Comment by musicalman** [comment]
問題ない。警告を説明すべきだった。
付属のテストc140.gwiを実行すると、サウンドチップがエンベロープをサポートしていないという警告が表示されます。しかし、封筒は機能するようです。したがって、私はそれが重要だとは思わない。

**Comment by kuma4649** [comment]
あ、おそらくエンベロープの定義にチップ名を指定していないからです。

無指定の場合はDCSGが指定されたことになるのですが、
DCSGの演奏データが無いと表示されます。

警告は出ますが使用する事は出来てしまうので
ますますわかりにくいですね。どうしようかな…

**Comment by musicalman** [comment]
分かりにくい場合は申し訳ありません。 Google翻訳がうまく機能するように単純に書きたいと思っていますが、完璧ではないことはわかっています。
あなたは正しかった。エンベロープでC140を指定すると、警告が消えます。私はそれに気付いたはずです。

**Comment by kuma4649** [comment]
いいえ、翻訳がわかりにくいのではないです。(^_^

「mmlの書式がわかりにくい」という意味です。
ですのでお気になさらず。

**Comment by kuma4649** [comment]
以下のような警告メッセージに変更しましたのでよろしくお願いします。

[Selected unsupported chip of the envelope. / Defined the unused chip envelope.]
