### ISSUE TITLE
odd behavior with _ command

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#23]
私は_コマンドで奇妙な動作を見つけていたので、先週、サポートされているほとんどのサウンドチップでテストしました。これが私が見つけたものです。
_を曲げに使用することは、HuC6280、K051649、およびYM2151ではサポートされていないようです。

pcm音源の場合：
1オクターブ未満のベンドは正常に機能します。ただし、ベンドが1オクターブ以上下がった場合、ベンドがcに達するとベンドにジャンプがあります。これは、vgm形式のほとんどのpcm音源で発生するようです。
これを防ぐには、ベンドを小さなベンドに分割し、＆コマンドで接続します。各ベンドがオクターブ以下の場合、ベンドは滑らかに聞こえます。

ym2413では、cに達すると常にベンドにジャンプがあります。あなたが上に曲がっているか、下に曲がっているかは関係ありません。

**Comment by kuma4649** [comment]
こちらも まだ確認出来てませんが
おそらくバグです。順に修正させていただきます！

**Comment by kuma4649** [comment]
ベンドの動作不良の修正が完了しました。ご確認ください。

**Comment by musicalman** [comment]
私のテストでは、すべてのpcm音源が正しく曲がっています！問題が見つかったらお知らせします。
Ym2413には小さな不具合が残っていますが、古いリリースよりも改善されています。
ベンドは、前述の音源ではまだサポートされていませんが、おそらく別の問題です。

**Comment by kuma4649** [comment]
>私のテストでは、すべてのpcm音源が正しく曲がっています
おぉ！良かった。。。

>Ym2413には小さな不具合が残っています
>ベンドは、前述の音源ではまだサポートされていません
すみません、何処か教えていただけませんか？

**Comment by musicalman** [comment]
ベンドはHuC6280、K051649、およびYM2151では機能しないようです。それらを使用しようとすると、次のエラーが表示されます。
継承先で要実装
Stack Trace:
   at Core.ClsChip.GetToneDoublerShift(partWork pw, Int32 octave, Char noteCmd, Int32 shift)
   at Core.ClsChip.AnalyzeBend(partWork pw, MML mml, Note note, Int32 ml)
   at Core.ClsChip.CmdNote(partWork pw, MML mml)
   at Core.ClsVgm.Commander(partWork pw, MML mml)
   at Core.ClsVgm.partWorkByteData(partWork pw)
   at Core.ClsVgm.AnalyzeAllPartCommand()
   at Core.ClsVgm.Vgm_getByteData(Dictionary`2 mmlData)
   at Core.Mml2vgm.Start()

**Comment by kuma4649** [comment]
よろしければ
エラーの出るデータを教えていただきますでしょうか…？

**Comment by musicalman** [comment]
確かに、私はあなたにそれを見せることができます。

**Comment by musicalman** [comment]
http://www.fileconvoy.com/gf.php?id=g287ed303812bce701000190390.130684390e2aa87b22ea8c7&sts=1566449867174556621177517e5b1e3a4d928a4d99d6b769d1ee

**Comment by kuma4649** [comment]
ありがとうございます！

調査しようと思います。

**Comment by kuma4649** [comment]
本件、修正完了しました。ご確認ください。

**Comment by musicalman** [comment]
すべて正常に動作しているようです。ありがとうございました！
