### ISSUE TITLE
build時のxcopy

### ISSUE THREAD

**Issue by erio2018** [kuma4649/mml2vgm#25]
お久しぶりです。
凄いペースで更新されてて、毎回不具合修正やIDEの完成度が上がっていくのを
楽しませてもらってます。

さて、恐らく最新の更新分からだと思われますが、PostBuildEventでxcopyを使うようになったためか、Linux(mono)環境だとBuildがエラーになっています。
見るに、bin/Release/*.*  を output/mml2vgm に手でコピーしてやれば良さげなので、こちらの環境も特殊ですし、問題というより報告レベルになりますので、認識だけしておいて頂ければ。

![Screenshot_20190825-074730](https://user-images.githubusercontent.com/35863829/63643888-59b8c500-c716-11e9-9a54-02d030ab3c60.png)

以下別件なのですが、vgmコマンド0x67〜のデータをファイルに落としてPCMデータ再利用しようと思い、差し当たってフォーマット等考慮せずに単純にファイル化してみましたが思ったよりノイジーな音になってしまいます。
そもそもオリジナルのwavファイルは復元可能なのでしょうか？
まだ取っ掛かりだけでwav読み込み部分とかソース読み込んでいないのでアライメントの違い等色々弄ってるんだろうなと言う予想しか出来ませんが、こうすれば簡単に復元できるよ、などの情報があれば教えていただきたいと思います。
こっちがメインになっちゃいましたが、よろしくお願いします。

**Comment by kuma4649** [comment]
おはようございます。
レポートありがとうございます😊
ビルド後にイベントとしてファイルをコピーするコマンドを追加しました。その影響が出ているということで間違いないです。
この形式はやめて、次回からはバッチファイルを作ってそれで代用しようと思います。

**Comment by kuma4649** [comment]
別件のほうですが
場合によっては復元可能です。
が 大体はそれなりに劣化するものと思って間違いないです。
以下は考えられる原因です
 ・バグのせいw
 ・元が16bitの音声である。
 ・音量指定している。(@Pコマンドにて音量変更するとそのロジックを通過します。)
  ・音源向けの加工を行なっている。
        adpcmやdpcm、音源独自の圧縮など。
  ・データ抽出時に使用しているツールの処理を通過している
  ・バグのせいw

**Comment by kuma4649** [comment]
セガpcmやqsound向けに取り込んだファイルは綺麗に復元できるパターンがあります

**Comment by erio2018** [comment]
バッチ化助かります。エラー無く綺麗にコンパイルしたいのは正直なところです^^;
あと、MDPlayerにそんな機能があったのですね。
Otherタブにダンプやwav出力を見つけました！これですね。。。
復元の方ですが、wavにする必然性は無く、再度mml2vgmで使えれば嬉しいのですが、そういった拡張は可能でしょうか？
「バグ」にはまだ当たっていない、と、思わ、れ、ます。。。
また、何かあったら報告させていただきます。

**Comment by kuma4649** [comment]
何も加工せずそのまま音源用PCMメモリに配置したいのであれば、
@PDや@PIコマンドを使用できるかもしれません。
帰宅したら調べてみます。

**Comment by erio2018** [comment]
おぉ、なるほどです。
このコマンドはそれ用な感じなのですね。
OKI5などのADPCMは未対応でしょうか？
rawデータでそのまま置くならイケる気がしますが。。。

@PDとPIコマンドをちょっと弄ってみます。
アドレス周りでまた質問するかもしれませんがよろしくお願いします！

**Comment by kuma4649** [comment]
mml2vgmはOKI5には対応してないのです。。。
あと、OKI5は確かADPCMでありながらストリーム系の音源だったような。。。
@pdと@piコマンドは音源自体がメモリを読む機能をもっているものだけになると思います。
(将来かわるかもしれないけど。。。)

**Comment by erio2018** [comment]
SegaPCMとC140で少し試してみました。
@PDでメモリにデータ置いて、@PIで音色アサインやら周波数設定して使う感じですね。
当初の目的はこれで十分に果たせそうです。
実装済みだったのは、流石です。
ありがとうございました。

**Comment by kuma4649** [comment]
pd,piとも要望をいただいて実装した機能です。
ご要望がありましたらお気軽にどうぞ仰ってくださいませ。

あと、TAG110にてバッチファイルに変更しました。
(が出力フォルダがgitの管理下に設置している。
管理外に設定しないとなぁ。。。どうやるんだろう)

**Comment by erio2018** [comment]
対応ありがとうございました。
いつも素早くてありがたいです。
