### ISSUE TITLE
QSound envelope behavior

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#26]
QSoundエンベロープにバグを見つけました。
エンベロープでQSoundを使用している場合、v65535をエンベロープと共に使用する必要があります。別の番号を使用する場合、またはvをまったく使用しない場合、ボリュームは大量にラップします。
いくつかのデータをご覧ください。
http://www.fileconvoy.com/gf.php?id=g7d7f6a8c9b177a121000194997.1313023cc17ec6b7e9fc630&sts=1568346137174556621194da85b24ca2a8ae02916095c5be6c59
また、提案があります。
ARの間、音量は常に最大に達するまで増加します。ただし、最大音量に到達したくない場合は、新しいパラメーターを使用できます。
エンベロープは次のようになります。
いいえ、SV、AR、AL、DR、SL、SR、RR、ST、ChipName
これは、音量が大きすぎると簡単に歪んでしまう音源を扱うのに便利です。しかし、他の用途があるかもしれません。
グローバルに実装するのがどれほど簡単かはわかりません。また、古い.gwiファイルとの互換性の問題を引き起こす可能性があります。

**Comment by kuma4649** [comment]
ご報告ありがとうございます。
調査します～

**Comment by kuma4649** [comment]
どうやらエンベロープが正しく動作していないようですね。

ご提案いただいている件。
恐らく、現在のバグが直れば必要ないと思われます。
(本来であればvコマンドで設定した値をエンベロープが超えることはありません。)

**Comment by musicalman** [comment]
うわー、私はそれを知りませんでした。説明してくれてありがとう。
K053260をテストしました。 QSoundと同じバグがあります。
他の音源はより良く機能します。すべてをテストしたわけではありませんが、それらの多くをチェックしました。

**Comment by kuma4649** [comment]
TAG112を作りましたので、お試しくださいませ。
ご参考までに、gwiを以下のように少し調整してテストしました。
K053260も同じバグでしたので修正しています(^_^;;

'{
ClockCount   =384
}
'@P0,"choir.wav",17100,25,QSound,0

   No,    SV, AR, DR,    SL,  SR,  RR,  ST, ChipName
'@E 0, 65535,  0, 10, 12000, 200,   1,  20, QSound

'Q01 T120 o4 l1 @0 @E0 EON q10

'Q01 l4v2000 c d e
'Q01   v6000 c d e

**Comment by kuma4649** [comment]
>他の音源はより良く機能します
テストありがとうございます。(T_T

**Comment by musicalman** [comment]
ありがとう、問題は修正されました！
QSoundについてもう1つ詳細があります。しかし、それは非常に小さなことです。
vコマンドを使用しない場合、すべての音源は最大音量を使用します。しかし、QSoundはより小さな音量を使用します。 v4000に近いと思いますが、正確に確認する方法がわかりません。
これがバグなのか、設計上の選択なのかわかりません。
特に封筒で作業する場合、混乱を引き起こす可能性があります。ただし、QSoundのボリュームは非常に大きくなる可能性があるため、これもある程度理にかなっています。

**Comment by kuma4649** [comment]
敢えて小さい音に設定しております(^_^
