### ISSUE TITLE
bank switching glitch

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#27]
これらのすべてのレポートをご迷惑をおかけして申し訳ありません。うまくいけば、これがしばらくの間最後のレポートになるでしょう。
C140、QSound、およびK053260を使用したバンク切り替えのバグを発見しました
このバグは、@ pトーン定義とバンク割り当てが同じ順序でない場合にのみ発生します。
これが発生すると、グリッチが聞こえるだけでなく、他のサンプルの不要な断片も聞こえます。
他のpcm音源は問題ないようです。
まだ@pdおよび@piコマンドを使用する自信はありません。したがって、私は@pのみを使用しています。
さらにデータを送信しています。うまくいけば、バグは明らかです。
http://www.fileconvoy.com/gf.php?id=gd605811ac0aae9de1000195361.13135869f4c27b0db9a93ad&sts=15686003521745566211223ab0d2b54ee6b81383f1451a1ef18d

**Comment by kuma4649** [comment]
ありがとうございます。早速調査します！

**Comment by kuma4649** [comment]
いただいたデータで返照がでるのはK053のみのようですが、
C140,QSoundもでしょうか？

**Comment by musicalman** [comment]
はい、k053には最も明らかな問題があります。
しかし、C140とQSoundを使用すると、サンプルの最後にポップ音がします。
@ p1と@ p2を交換することで、ポップ音を除去できます。
例として、C140を使用した別のgwiファイルを次に示します。
ただし、このgwiファイルはQSoundとK <053の問題も修正します。

'@P0,"cymbal.wav",21390,100,C140
'@P1,"snare.wav",21390,100,C140
'@P2,"guitar.wav",21390,100,C140

'Y01 T60 o4 l1 @0 c @2 c @1 c

**Comment by kuma4649** [comment]
成程、キーオフしたときにノイズ音がでるということですね。
引き続き、調査します

**Comment by kuma4649** [comment]
TAG114で修正しました。
お試しくださいませ。

**Comment by musicalman** [comment]
確認済み。修正済みです！
