### ISSUE TITLE
when HuC6280 should be silent

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#29]
HuC6280で小さな異常を見つけました。
沈黙が必要なときに音が聞こえます。
たとえば、rコマンド中、またはエンベロープの有効期限が切れたとき。かすかな音がまだ聞こえます。
何が起こっているのかを知るのに役立つ場合に備えて、データを送信しています。
http://www.fileconvoy.com/gf.php?id=g633cf20bc5e782571000198846.13182438e9a1eaf4666fa22&sts=157001800117455662114966dff16477d8b2e67c321e1d785200

**Comment by kuma4649** [comment]
ありがとうございます。
確認します。

**Comment by kuma4649** [comment]
TAG118を公開しました。
KeyOffすべきところをKeyOnしていました。。。
ご確認ください。

**Comment by kuma4649** [comment]
更にTAG119を公開しました。。。
申し訳ありませんが、こちらをご確認ください。

**Comment by musicalman** [comment]
心配ない！
TAG 119では、問題は見つかりませんでした。
