### ISSUE TITLE
rf5c164 bug and request

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#30]
rf5cでエンベロープを使用すると、バグが発生する可能性があります。
次のメモの前にRRの有効期限が切れていない場合、サンプルは適切にキーオフされません。
以下にデータを示します。
http://www.fileconvoy.com/gf.php?id=g6af80e9df0ed09c21000201677.1322601e9d4f2cbc9c23127&sts=1571229911174556621140abf687886604815a08b5cde419bddd

また、rf5cに関するリクエストがあります。
o3 cは8KHZに固定されています。 qsoundとc140でできるのと同じ方法でこれを変更することは有益だと思います。これは可能ですか、それとも難しすぎますか。
ありがとう。

**Comment by kuma4649** [comment]
こんにちは。返事が遅れてすみません。
これから調査しますのでよろしくお願いします。

**Comment by kuma4649** [comment]
TAG126で対応させていただきました！
ご確認お願い致します。

o3 8kHzの件。
ちょっと忘れてしまったのですが、
指定可能な値の範囲をみて調整したようなきがするので
このままで良いかなと思ってます。
しかしながら、他のChipと可能な限り同じ感覚で使えるようにしたいとも思っています。
どうしようかな。。。

**Comment by musicalman** [comment]
応答が遅くなる心配はありません。
この問題はTAG126で修正されました！
o3 8kHzの件。
私はあなたをよく理解できませんでした。私の翻訳は悪かったと思います。
私がそれを言った理由は、いくつかのサンプルが正しいノートを演奏しないということです。 rf5cでは、KとDを使用してそれらを修正する必要がありますが、これは厄介です。ただし、c140およびqsoundでは、再生レートを変更するだけで修正されます。
もちろん、pcm音源には他の選択肢もあります。ですから、rf5cを変更したくない場合は理解しています。

**Comment by kuma4649** [comment]
音程が狂っている
ということでしょうか？

**Comment by kuma4649** [comment]
TAG127でrf5cの周波数を参照するよう修正しました。

**Comment by musicalman** [comment]
ありがとうございました！
