### ISSUE TITLE
サンプルデータの大文字→小文字の名前変更を行った後、フォルダービュー上で大文字と小文字のファイルが両方あるように表示されてしまう

### ISSUE THREAD

**Issue by sdhizumi** [kuma4649/mml2vgm#55]
Windows10上で動作しているmml2vgmにて、
Crush_18500.wav を crush_18500.wav へエクスプローラー上でリネームした後に、mml2vgm上のフォルダーツリーで更新ボタンをクリックすると、画像の様に両方のファイルが存在するかのような状態になってしまいました。

ダブルクリックして行えるwavのプレビュー機能は、リネーム後・前どちらの表示名からでも動作しました。

mml2vgmを再起動すると、ツリーが完全に再読み込みされるのか、リネーム後の表示名のみ残りました。

![image](https://user-images.githubusercontent.com/31327231/80070059-544d9c00-857d-11ea-8f14-a842eae1102f.png)

**Comment by kuma4649** [comment]
windows特有の挙動を見落としていることからおこるバグかと思われます。
(プログラムがファイルの重複を調べる際に、大文字小文字が異なっていても互いが同じファイルであることがあることを考慮していない)

**Comment by sdhizumi** [comment]
PlayおよびJSolo+Play表示になることを確認しました。ありがとうございますー！

**Comment by sdhizumi** [comment]
ごめんなさい別件でした(twitterでの方の報告をしてしまいました)
適当なファイルをリネームして更新を掛けて、重複表示されないことが確認できました！改めてありがとうございます！

**Comment by kuma4649** [comment]
承知しましたー
