### ISSUE TITLE
C352?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#60]
こんにちは、
他にもたくさんのpcm音源があることは知っていますが、ナムコC352チップ（C140の後継）を検討しましたか？とてもいい音だと思います。また、32チャネルを備えています。
追加したくない場合は、心配しないでください！ただ聞きたかっただけです。
読んでくれてありがとう、そして良い一日を！

**Comment by kuma4649** [comment]
こんにちは！
良いですねC352！
対応したい気持ちはあるのですが、
今のところPCMの変換方法がわからなく困っています。

**Comment by musicalman** [comment]
ああ、残念です。手伝うことができるかどうか本当にわかりませんが、やってみます。
Vgmrips.netによると、C352は8ビットPCMサンプルと8ビットµ-lawサンプルを使用できます。
C352サンプルを抽出するユーティリティも見つけました。試してみたところ、うまくいきました。それはオープンソースなので、あなたを助けるかもしれません。
必要に応じて、https：//ctr.tasossah.com/vgm/mulaw.zipからダウンロードできます。

**Comment by kuma4649** [comment]
ありがとうございます。
研究させていただきます！

**Comment by kuma4649** [comment]
soxを使うと変換できるようです!

**Comment by musicalman** [comment]
いいね！必要に応じてsoxを使用して変換を実行してもかまいません。
C352の使い方や技術仕様の見つけ方がわかりません。しかし、私はあなたがあなたが必要な情報を見つけることができることを望みます。

**Comment by kuma4649** [comment]
その後色々試しています。
soxを使用するとC352向けのmulawは作れないことがわかりました。
でも、運よくIan Karlssonさんのご協力も有り、
自前で変換できそうです！

**Comment by musicalman** [comment]
おお、それは素晴らしいです！イアン・カールソンの解決が成功することを願っています！
ちなみに、mulaw変換が難しすぎると思うなら、C352は標準の8ビットPCMをサポートしていると思います。
しかし、mulawの方が音が良いと聞きました。

**Comment by kuma4649** [comment]
C352に対応しましたー

**Comment by musicalman** [comment]
どうもありがとうございました！
小さなバグを見つけました。 _コマンドはエラーになります。
y1000,0はフォワードループを使用し、y1000,1は双方向ループを使用していることに気付きました。他のyn1、n2コマンドを使用できるように、追加のドキュメントの場所を知っていますか？
具体的には、キーオン時にC352が実行するボリュームフェードを無効にしたいと思います。しかし、これが可能かどうかはわかりません。

**Comment by kuma4649** [comment]
ポルタメントでしょうか。ちょっと調べてみます。
y1000,x はとりあえず追加した暫定機能です;P
あと、キーオン時のボリュームフェードは恐らく、やめさせることはできないと思います。

**Comment by kuma4649** [comment]
↓参考まで
https://github.com/kuma4649/MDSound/blob/master/MDSound/MDSound/c352.cs#L86

**Comment by kuma4649** [comment]
ポルタメント修正しましたー

**Comment by musicalman** [comment]
ポルタメントが修正されました！
私はコードを見て、誤ってフィルターを無効にする方法、チャンネルを反転させる方法、ノイズを生成する方法などを考え出しました。
一部のゲームではキーオンフェードが無効になっていると思いますが、フェードが微妙なのでわかりません。
c352_ramp_volume関数を見つけましたが、その機能を理解するためのコーディングスキルがありません。

**Comment by superctr** [comment]
The ramp function reduces the popping noises by increasing/decreasing the volume by 2 every time the sample address is incremented (or once every time the MSB of the phase counter flips), until it reaches the target volume. The best way to reduce the ramping effect is to increase the sample playback frequency.

I experimented with disabling ramping when the "C352_FLG_FILTER" flag is 1, but I don't know if the real chip does this too. (It would make sense since the filter is usually only off when "WSG" samples are used).

**Comment by musicalman** [comment]
That makes sense.
In mml2vgm y1000,0 and y1000,4 commands seem to change "C352_FLG_FILTER"
The ramping seems to be enabled in either case, at least when I tried it.
I'm not too sure if it can be turned on/off in the C352 itself. I hope it can but I don't know enough about it to say.

**Comment by superctr** [comment]
To clarify, I refer to the C352 emulator in QuattroPlay, which does have this C352_FLG_FILTER flag behavior. It seems like that has not been implemented in MDPlayer yet.

If you don't mind a little bit of delay, it's possible to insert ~128 bytes of silence in the beginning of the sample. By that time, the ramping should already have completed.

**Comment by musicalman** [comment]
Yeah, delaying some samples isn't a bad idea.
I tried MD Player and in_vgm/vgmplay and got the same results with both. I haven't tried Quattroplay though.

**Comment by kuma4649** [comment]
QuattroPlayのソースを参照しました。
MDSoundも同じ動作をするようにC352_FLG_FILTERを参照するようにしましょうか？

**Comment by superctr** [comment]
Yes, that would be good. Also, the mulaw code [here](https://github.com/kuma4649/MDSound/blob/master/MDSound/MDSound/c352.cs#L181) could be updated to use the new table.

**Comment by kuma4649** [comment]
了解です。合わせて修正します。

**Comment by kuma4649** [comment]
TAG223で対応しました

**Comment by musicalman** [comment]
MDPlayerは期待どおりに動作します。

**Comment by kuma4649** [comment]
mml2vgmしかなおしてないっす～;P

**Comment by musicalman** [comment]
申し訳ありませんが、mml2vgmは再生にMDPlayerを使用していると思いました。
スレッドを閉じますか？
