### ISSUE TITLE
"Not found M98DotNET."

### ISSUE THREAD

**Issue by pedipanol** [kuma4649/mml2vgm#61]
I get this error when pressing F6 to compile m98 .muc files. Am I doing something wrong?

**Comment by kuma4649** [comment]
ダウンロードしたファイルがOSによりロックされることがあります。
もしかするとそれが原因かもしれません。
先ずはこのことを確認お願いしますorz

参考：
https://www.atmarkit.co.jp/ait/articles/1603/11/news050.html

**Comment by kuma4649** [comment]
如何でしたでしょうか？

**Comment by pedipanol** [comment]
That might have been the cause, just downloading the newest version and loading from a different folder solved it

**Comment by kuma4649** [comment]
よかった！
また何かございましたらご連絡ください。
