### ISSUE TITLE
OPL3 Instrument Bug

### ISSUE THREAD

**Issue by GTheGuardian** [kuma4649/mml2vgm#62]
(For reference, I used the latest release (labeled TAG217) during the testing)

I appear to have noticed a possible error with the OPL3 instrument definition.

Right now, The MML Command Memo specifies the format for 2-op OPL3 instruments as such.

```
'@ L No
'@ AR DR SL RR KSL TL MT AM VIB EGT KSR WS
'@ AR DR SL RR KSL TL MT AM VIB EGT KSR WS
'@ CNT FB
```

However, during my testing, I found out that KSR appears to actually act as Waveform Select (KSR appears to be only turned on when KSL > 0) while WS appears to have no effect.

I did created a simple test GWI file for demonstration. 

https://www.dropbox.com/s/fx1udz3nyon618q/opl3_bug.7z?dl=1

**Comment by kuma4649** [comment]
修正しましたー
TAG218

**Comment by GTheGuardian** [comment]
Thank you very much for fixing it.
