### ISSUE TITLE
(OPL2) Missing Waveform Enable Command

### ISSUE THREAD

**Issue by GTheGuardian** [kuma4649/mml2vgm#63]
(Release Tested: TAG222)

I found a bug with the OPL2 implementation.

It appears that mml2vgm is forgetting to write the "Waveform Select: Enable" command (5A 01 20), which ends up breaking instruments that use the extra waveforms. 
(The OPL2 by default has the extra waveforms disabled in order to keep backwards compatibility with YM3526, which had no additional waveforms other than Sine Wave.)

**Comment by kuma4649** [comment]
ありがとうございます。

初期化時に、アドレス$01へデータ$20を送信するよう修正します。

**Comment by kuma4649** [comment]
TAG223で対応しました

**Comment by GTheGuardian** [comment]
Thank you. I can confirm that TAG223 fixed this issue.
