### ISSUE TITLE
k053260 request

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#64]
こんにちは、
K053260では、他のpcmチップと同様にBaseFreqを変更したいと思います。
これは可能ですか？
ありがとう！

**Comment by kuma4649** [comment]
BaseFreqとは、チップのMasterClockのことでよろしいでしょうか。
今のところ全てのチップのマスタークロックは変更できるような機能を用意していません。。。

よろしければ用途を教えていただいてよろしいでしょうか。

**Comment by musicalman** [comment]
私はcと書いたときにcが聞こえるように周波数を調整しようとしていました。つまり、ノートの周波数が固定されないことを望んでいました。
レートがマスタークロックに基づいていることを知りませんでした。そのため、QSound、C352などのようにBaseFreqを変更することがより困難になる可能性があります。

**Comment by kuma4649** [comment]
https://github.com/kuma4649/mml2vgm/blob/master/mml2vgm/mml2vgm/sample/K053260/testK053260.gwi

mml 2vgmで操作できるかという事でしょうか。
一応対応してます。
サンプルです

**Comment by musicalman** [comment]
すみません、最後のメッセージがよくわかりません。おそらくGoogle翻訳は不明確でした...

**Comment by knight-ryu12** [comment]
Q: do you mean controlling via mml2vgm?

2020年6月8日(月) 20:38 musicalman <notifications@github.com>:

**Comment by musicalman** [comment]
Yes. For example if my wav file plays a c at 13500, I could use:
'@ P 0,"test.wav",13500,100,K053260

**Comment by kuma4649** [comment]
あー、なるほど。
musicalmanさんの上げた例での13500という値は
恐らく無視されています。
一部のチップはそこを参照するのもあるのですが基本そのパラメータは無視です。

**Comment by musicalman** [comment]
はい、そうです。この場合、13500は無視されます。
この動作を変更できますか、それともK053260の制限ですか？

**Comment by kuma4649** [comment]
K053260にはそのような制限はありません。
単純にmml2vgmの仕様です。

少し考えさせてください。。。

**Comment by kuma4649** [comment]
修正完了しました。ご確認ください！

**Comment by musicalman** [comment]
ありがとうございました！うまくいっているようです。
