### ISSUE TITLE
キーエンベロープの実装を要求する (requesting implementation of note/key envelope)

### ISSUE THREAD

**Issue by ultrasound1372** [kuma4649/mml2vgm#66]
PSGのスライドやドラムパターンなど、一般的に必要なタイプのピッチエンベロープは、ベンドコマンドとLFOをワンショットモードで行うことができますが、PSGでは特に有用な別のタイプのエンベロープがありますが、他のmmlコンパイラはサポートしていますが、これはそうではありません。私はreferringノートの封筒を参照していますが、翻訳者は「ノート」という言葉を破っています。これは、MCK シリーズのコンパイラで次のように表されます。
    @ EN 0 = {0 | 3 4 -7}
または、現在のノートではなくスタート ノートに対するすべての変更を行う場合
    @ EN 0 = {| 0 3 7}
これはarpsに使用され、非常に限られたチップで動作する人々の多くが使用する和音を演奏するメカニズムであり、メロディ、コード、ベース、ドラムなどに分割されたチャンネル(SN76489、AY3-8910など)があります。ZXスペクトラムのために作られたゲームでこれをたくさん見ることができますし、チップ音楽の共通のテーマです。エンベロープは必ずしもループする必要はありません。また、これらの同じチップに対する摘み取りのような攻撃を作成するためにも使用できます。'|' はループを意味する文字です。このエンベロープ内のオフセットは、エンベロープがトリガーされた開始音に対して相対的に作業するか、現在のノートの値が半音で測定されるかに関係なく、使用します。これらのコンパイラのほとんどは、1秒間に60回マクロを踏み抜いたので、arp速度はここではるかに速く、時計で書き出clockすと非常に時間がかかり、扱いにくくなります。したがって、次のような構文を提案します。
    '@ EN 0 = {0 10 | 3 10 4 10 -7 10} ;最初の数字は半音オフセット、秒は保持するクロック数です。ループに使用されるパイプ文字。相対モードのこのシーケンスは、ほとんどのキーでマイナーな 3 番目のコードを作成します。
    'A1 l8 Q4 @EN0 ENON cccrccc<a+> ENOF
現在のノートではなく開始音に対して相対で使用している場合、シーケンスは {| 0 10 3 10 7 10} になります。
プラック音を出すために、次のようなarpを作ることができます。
    '@ EN 1 = {12 10 0 10}
これはオクターブより高いブリープを作成し、すぐにノートにスナップし、スライドはありません。これが何らかの方法で実装されている場合は、それがオフセットから分離されたクロックカウントを指定するかどうか、'#'文字でオフセットを指定するか、何であれ、ループインジケータがない場合、エンベロープが最後のプログラム値に達すると、メモが解放されるか、エンベロープが無効になるまでその値を保持する必要があることに注意してください。メモを再起動すると、最初から封筒が開始されます。さらに、指定されたすべてのノートは、結合されたかのように扱われる必要があるため、ボリューム エンベロープが有効な場合は、ノートエンベロープ値が変更されるたびにボリュームエンベロープを再起動せず、ノートがリリースされるまで維持フェーズにとどまる可能性があります。これは mml で手作業で実装できますがmml、コードは不必要に乱雑で冗長です。
これについて私に戻ってください。このメッセージは、翻訳された日本語と英語の両方で投稿されるため、翻訳のエラーが解決される可能性があります。

  
  
While pitch envelopes of the types we generally need, like slides and drum patterns on PSGs, can be accomplished with the bend command and the LFO in one-shot mode, there is another type of envelope that you will find useful especially on PSGs, which other mml compilers I have used support but which this one does not. I am referring to the note envelope, though the translator has broken the word "note." This is represented in the MCK series of compilers by the following.
    @ EN 0 = {0 | 3 4 -7}
or if you make all changes relative to the start note rather than the current
    @ EN 0 = {| 0 3 7}
This is used for arps, and is a mechanism of playing chords used by many of those working with very limited chips, where they may have channels split out into melody, chords, bass and drums, for example the SN76489 and the AY3-8910. You may see this a lot in games made for the ZX Spectrum, and it is a common theme in chip music. Note that the envelope need not always loop. It can also be used to create pluck-like attacks on these same chips. The '|' character is what signifies the loop. The offsets in this envelope, whether you work relative to the starting note that the envelope triggered on or the current note value is measured in semitones. Most of these compilers stepped through their macros 60 times a second, so the arp speeds you could get would be much faster here, and if you were to write them out clock by clock they would get very lengthy and unwieldy. I therefore propose a syntax like the following.
    '@ EN 0 = {0 10 | 3 10 4 10 -7 10} ; first number is semitone offset, second is number of clocks to hold. Pipe character used for loop. This sequence in relative mode would create a minor third chord in most keys.
    'A1 l8 Q4 @EN0 ENON cccrccc<a+> ENOF
If you were using relative to the starting note rather than the current note, the sequence would be {| 0 10 3 10 7 10}
To make a pluck sound, you could make an arp like the following.
    '@ EN 1 = {12 10 0 10}
This would create an octave higher bleep and then snap to the note immediately, there is no slide. It should be noted that if this is implemented in whatever way you see useful, whether that be specifying the clock count separated from the offset by a '#' character or whatever, that in the absence of a loop indicator, once an envelope has reached its last programmed value it should hold that value until the note is released or the envelope is disabled. Restarting the note would start the envelope from the beginning. Furthermore, all notes specified should be treated as if tied together, so if a volume envelope is in effect it might stay at the sustain phase until the note is released, not restarting the volume envelope every time the note envelope value changes. This can be implemented by hand in mml but the code would be unnecessarily messy and verbose.
Please get back to me on this. This message will be posted in both translated Japanese and the source English, so that any errors in the translation may possibly be resolved.

**Comment by ultrasound1372** [comment]
添付されているのは、この機能で許可される種類のことを利用するvgmファイルの例です。 ZX Spectrumゲームでは、トラック1のように独自の音色の違いを提供するためにどのように使用されているか、またはトラック7のコードに注意してください。これらは、正方形のLFOで実行できる場合があります。しかし、これは3つのノートを使用するため、マスターシステムのトラッカーチューンには機能しません。
[vgm_with_arps.zip](https://github.com/kuma4649/mml2vgm/files/4894733/vgm_with_arps.zip)

**Comment by kuma4649** [comment]
例えば、↓のようなmmlの場合
ClockCount =192
'@ EN 0 = { 0 10 | 1 10 1 10 -2 10 }
'A q0@EN0 l4 c

以下の２つの例AとBどちらの演奏になりますか？
例A)
ClockCount =192
'A q0l#10 c&c+&d&c&c+#8

例B)
ClockCount =192
'A q0l#10 c c+ d c c+#8

PSG系の場合、差は小さいのですが、
FMやPCMの場合、キーオンする/しないの差がでます。

**Comment by ultrasound1372** [comment]
例Aを再生すると、自分でPSGチャンネルに適用したボリュームエンベロープであれ、FMチップに組み込まれたエンベロープであれ、ノートが1つだけ受け取ったかのように動作するエンベロープは、ピッチが変わるだけです。これらのチップは、キーのオンとオフを変更することなく、それを行うことができますか?私は、XPMCKでコンパイルされたメガドライブのVGMファイルのこの例で与えられたように、彼らは、例のファイルの一つとして、そう思います。
[xps3.zip](https://github.com/kuma4649/mml2vgm/files/4898157/xps3.zip)

**Comment by kuma4649** [comment]
Which one is closer to your ideal movement?
A? Or is it B?

**Comment by ultrasound1372** [comment]
ああ、それは翻訳で失われたに違いない。例 A は理想的です。

**Comment by kuma4649** [comment]
うーん。。。
本来のアルペジオであれば、キーオンしなおすのも有りなんですけど、
分散した和音として扱うのであれば、タイなんですよねぇ。。。
(^_^;;;;

**Comment by kuma4649** [comment]
No   tie  q     delta clock loopMark ...(repeat delta & clock) 
'@ ARP  0     0  14        0    24        |  -5 24  5 24 ; 否tieモード時はq値を指定する
'@ ARP  1     0  14        0    24        |  -4 24  4    ; 最後のclockは省略可能(直前のclockになる)

       No   tie        delta clock loopMark ...(repeat delta & clock)
'@ ARP  2     1            0    24        |  -5 24  5 24 ; tieモード時はq値を指定してはいけない!
'@ ARP  3     1            0    24        |  -4 24  4 24

'@ ARP  4 0 4  0 12 | 7 12  5 12 -12 12


'Cn1 T110

'F1 @0D0p3v115o6l8q0
'F1 APON AP0c1 < AP1b1 > 
'F1      AP2c1 < AP3b1 > 

'F1 @1D0p3v120o6l16q0
'F1 AP4 
'F1 APON e#180 APOF b     
'F1 APON d#144 APOF daga  
'F1 APON e#180 APOF b     
'F1 APON d#144 APOF da>cd<

**Comment by kuma4649** [comment]
こんな感じに実装しました

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1281811127282720769?s=20

**Comment by kuma4649** [comment]
https://kuma4649.github.io/index.html

実装しました

**Comment by ultrasound1372** [comment]
それが何らかのスライドショーだったら、私は私の失明のためにそれを見ることができません。では、'@ ARP def_numのネクタイのように実装されているのでしょうか?そして、ノートの値は開始音または現在のノートに対して相対的ですか?

**Comment by kuma4649** [comment]
上に示したmmlを演奏しているだけの動画です。
ノートは直前の音を基準に相対です。

**Comment by kuma4649** [comment]
こちら、クローズします
