### ISSUE TITLE
arp bug/unexpected behavior

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#67]
新しいarpコマンドをテストしていたところ、いくつかのバグが見つかりました。
SN76489およびHuC6280：エンベロープを使用すると、arp定義でqコマンドが無視される
RF5C164：arpを使用するとコンパイルが失敗する
一般的な観察：
ARPタイモードが0に設定されている場合、ノートはタイされませんが、エンベロープはタイされます。
これが意図されているのかわからないので、お願いしたいと思いました。
これまでに、psg、wsg、およびpcmのみをテストしました。したがって、すべてのチップがテストされたわけではありません。
必要な場合は、ここに.gwiデータの例を示します。
https://cp.sync.com/dl/d095c7d40/byv3deyi-thw4cykd-ac35rvee-jmdwur3n

**Comment by kuma4649** [comment]
ありがとうございます。修正しましたー

https://kuma4649.github.io/index.html

**Comment by musicalman** [comment]
ありがとう、それは今うまく機能しているようです
