### ISSUE TITLE
LICENSE concern

### ISSUE THREAD

**Issue by atsushieno** [kuma4649/mml2vgm#7]
Are those files authored and released under certain open source license? I know some classic emulator-based sound chip implementations are ported from non-free license code and these sources without licenses worry us.

**Comment by atsushieno** [comment]
わたしのおすすめでよければ（と言っても多くの方が同意してくれると思いますが）、Microsoftが.NET Coreなどでも使っているMITライセンスがよいと思います https://github.com/dotnet/corefx/blob/master/LICENSE.TXT

（MITのほか、Apache2, GPL/LGPLなども提示された条件を満たしています。いずれの場合も、使いまわすなら、copyrightの行の権利者名を自分のものに書き換える必要があります。）

neogeodevのwikiはpublic domainであると書かれているので、MITライセンスのもとで配布しても大丈夫です。

とりあえず問題にはならなそうなので、（できればLICENSE.txtなどを追加していただいて）このissueは閉じてくださいませ。

**Comment by atsushieno** [comment]
使いたい場面がありましたら是非どうぞ〜

**Comment by kuma4649** [comment]
ありがとうございます！
monoの技術も興味があるのでそれとあわせてソースを覗かせて頂こうと思います。。。

対応完了しました。クローズさせていただきます。
