### ISSUE TITLE
detune range

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#70]
デチューンコマンドで何か面白いことに気づきました。
C352などの一部のサウンドチップには16ビット範囲がありますが、他のほとんどのチップには離調用に8ビット範囲しかありません。
ほとんどのチップでは8ビット範囲で十分だと思いますが、C140やQsoundなどの一部のチップでは、D127が十分に大きくない場合があります。
回避策は、同じサンプルを異なるレートで2回ロードすることです。しかし、これは効率的ではないようです。
他の一部またはすべてのチップのデチューンを16ビット範囲に増やすことは価値があると思いますか？

**Comment by kuma4649** [comment]
あわわ。。。ちょっと見直しが必要みたいですねww
ありがとうございます。

**Comment by kuma4649** [comment]
TAG296にて修正しましたー
ご確認ください。

**Comment by musicalman** [comment]
うまく機能しているようです。ありがとう！
