### ISSUE TITLE
arpeggios

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#71]
ウェーブテーブルサウンドチップ（HuC6280およびK051649）の新機能のアイデアがあります。
説明するのは少し難しいです。 言語翻訳がそれを台無しにしないことを願っています。
基本的に、私の考えは、ノートの演奏に合わせてウェーブテーブルを変更することです。
@hコマンドを使用してウェーブテーブルを通常どおりに定義しますが、パターンを使用して、時間の経過とともにウェーブテーブルを変更できます。
パターンの各ステップには、ウェーブインデックスとクロックティック単位の長さが含まれます。 さらに、ループポイントをパターンに含めることができます。 アルペジオコマンドに似ています。
これにより、パルス幅変調、フィルタースイープなどの興味深い効果が可能になります。
楽しみのために、手動でこれを実行して、どのように聞こえるかを確認しました。
これが私が使用したgwiデータであり、私が考えている種類の効果を見ることができます。
http://www.fileconvoy.com/dfl.php?id=g48cdcde7c49bc30d10002960193773bb8c34bab718
どう思いますか？

**Comment by kuma4649** [comment]
なるほど。。。
時間経過とともに音色が切り替わる感じですね。

アルペジオと同様に変化を定義して使用する感じかなぁ。
アルペジオ定義中に音色を指定できるようにすればよいのでは？

**Comment by musicalman** [comment]
はい、それは面白いでしょう。
私が正しく理解していれば、あなたはトーンチェンジとアルペジオを同じ定義に入れることを考えました。
しかし、おそらくそれらは別々でなければなりません。
このように、トーンの変化とアルペジオは独立していて、異なるループポイント、ステップ長などを持つことができます。
しかし、それが難しすぎるとしたら、私は理解しています。

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1327425092553371648?s=20

こんな感じで使用できるようにしたいなーと。

**Comment by musicalman** [comment]
申し訳ありませんが、理解できません。
あなたのTwitterリンクを見ました。
私は何をすべきか？

**Comment by kuma4649** [comment]
あ、ごめんなさい、特にあなたが何をするべきかはありません。
Twitterでつぶやきながら考えをまとめたかっただけですのでお気になさらず。

**Comment by kuma4649** [comment]
https://twitter.com/kumakumakumaT_T/status/1327453758448570369?s=20

このように変更します。
・他のコマンドに対応できるようにしました。
・多数同時反映ができるようにしました。

**Comment by musicalman** [comment]
サウンドチップの量が多く、違いがあるため、難しいかもしれません。
だから私はウェーブテーブルサウンドチップで音色を変えることだけに言及しました:)
しかし、他のコマンドを組み込むことは面白そうです！

**Comment by kuma4649** [comment]
huc6280.gwi
k051649.gwi
ですがmml2vgmのサンプルとして収録させていただいてよろしいでしょうか。
少し調整もさせていただくのですが。

**Comment by musicalman** [comment]
確かに、あなたはそれらを使うことができます。
トーンの変化がどのように聞こえるかを確認するための簡単なテストとしてのみ作成しました。

**Comment by kuma4649** [comment]
リリースしましたー
ご確認ください

**Comment by musicalman** [comment]
おかげで、それはうまくいきます！
残念ながら、小さなバグを見つけました。
ソフトウェアLFOを使用している場合、ワンショット波形を使用すると、トーンアルペジオが競合しているように見えます。
音色が変わると、音量やピッチも変わります。
他のLFO波形はうまく機能しています。
これが理にかなっているかどうかはわかりません。 もっとよく説明できたらいいのに:(

**Comment by kuma4649** [comment]
すみません、mmlを提示していただくことは可能でしょうか

**Comment by musicalman** [comment]
これはhuc6280のピッチlfoのサンプルですが、k051649も影響を受けます。
http://www.fileconvoy.com/dfl.php?id=g70805ff1d23f86a9100029754525ecf982da3a8684

**Comment by kuma4649** [comment]
なるほど。。。調査します！

**Comment by kuma4649** [comment]
修正しました。ご確認ください！

**Comment by musicalman** [comment]
修正されました！
しかし、申し訳ありませんが、さらに2つのバグが見つかりました。 私は昨日それらを見つけなかったと思います。
1. HuC6280では、ボリュームLFOが壊れています。 すべての波形が影響を受けます。
2.トーンアルペジオと一緒にソフトウェアエンベロープを使用しようとすると、vgmがコンパイルされないことがよくあります。 これはHuC6280とK051649の両方に影響すると思います。
プログラムはクラッシュしませんが、ツールバーが消え、プログラムを閉じるためにmml2vgm.exeを強制的に終了する必要があります。
次に例を示します。
http://www.fileconvoy.com/dfl.php?id=g0445f2f7c9c79e1810002976256aeef819b1697573

**Comment by kuma4649** [comment]
ありがとうございます。引き続き調査します！

**Comment by kuma4649** [comment]
envelope.gwi
 原因：CARの定義がないのに使用した為。 -> エラーチェックを強化しました
one-shot.gwi
 特に問題なし？定義で音色を全て同じのを指定してみるとわかりやすいかも？
'@CAR0,@,#1,0,#3,|,3,3,3,3,3,3,3,3,3

また、「|」のあとには「,」を入れるようにお願いします。

上記とは別に「|」で定義が終わるとハングするバグを修正しました。

**Comment by musicalman** [comment]
申し訳ありませんが、封筒のバグは私の側の間違いでした！ ご説明ありがとうございます。
はい、LFOをより明確にすべきでした。
トーンアルペジオを使用すると、LFOの音量が途切れ途切れになります。
より簡単な例を次に示します。
http://www.fileconvoy.com/dfl.php?id=gb10bf072bd1b3e7b1000297645e0ceb8000a1a14af

**Comment by kuma4649** [comment]
HuCは音色を切り替えるごとに強制的にKeyOffされます。
なのでKeyOnをやりなおすような動きにしています。その影響かもしれません。

**Comment by musicalman** [comment]
ああ、それは理にかなっています。
おそらくこれは妥協する必要がありますか？

**Comment by kuma4649** [comment]
そうですね...
「仕様」
ということでお願いします

**Comment by musicalman** [comment]
翻訳は少し不明確です。 これは放っておくべきだと言っているのですか？

**Comment by kuma4649** [comment]
chipの動作によるものだから、
諦めるしか無いと言っていますw

**Comment by musicalman** [comment]
ああ。 わかります。
その場合、他に議論することはないので、これを閉じます。 きっと新機能を生かしていきます！

**Comment by kuma4649** [comment]
早速なんですがフォーマット変更しようと思います。

**Comment by kuma4649** [comment]
■ コマンドアルペジオ定義

'@ CAR No , Cmd , Sync , Data ...
No 定義番号(0-255)
Cmd @ とりあえず音色のみ。
Sync  ( 
   0 :  毎回キーオン/オフに合わせてシーケンスが開始されます  
   1 :  キーオン/オフに関係なくシーケンスを開始します。
)
Data n | @n | @in | @en | @nn | @rn | @an | @vn

**Comment by kuma4649** [comment]
このように、CmdとDataの間にSyncを追加しますのでよろしくお願いします。

**Comment by musicalman** [comment]
面白そうですね。
新しいSyncオプションが好きです。
私はデータに少し混乱しています：n | @n | @In | @En | @Nn | @Rn | @An | @Wn
ただし、既存の実装と似ています。
それで、Sync部分が唯一の変更ですよね？

**Comment by kuma4649** [comment]
そうですね！
n | @n | @in | @en | @nn | @rn | @an | @wn
↑これはFM音源などは色々な@コマンドが使えるので、それに合わせて用意しています。

近いうちにパン(pコマンド)にも対応させようと思ってます。
↓こんな感じになります
'@ CAR 0 , p , 1 , | , "4,4" , #4 , "3,4" , #4 , "2,4" , #4 , "1,4" , #4 , "0,4" , #4 , "1,4" , #4 , "2,4" , #4 , "3,4"

YM2609やHucの様にパラメータが二つある場合は「"」で括る必要があります。

**Comment by kuma4649** [comment]
リリースしましたー
ご確認ください

**Comment by musicalman** [comment]
パンアルペジオをテストしました。
HuC6280には制限がありますが、それ以外の点ではサウンドチップは正常に機能しています。
しかし、K053260にはバグがあります。
最初の音はいいですね。 しかし、2番目の音符の後、アルペジオによってサンプルが再起動し、スタッター効果が発生します。
http://www.fileconvoy.com/dfl.php?id=gc25a314a7c54243a100029819175f6e04674bdae6c
これは制限ですか？

**Comment by kuma4649** [comment]
あらら。。なんでしょうね。調査します

**Comment by kuma4649** [comment]
修正しました。ご確認ください！

**Comment by musicalman** [comment]
バグは修正されましたが、残念ながらチップに新しい問題があります。
音符の間にギャップがある場合、それはうまく機能します。
しかし、ギャップがない場合、ノートは一緒に結ばれます。
たとえば、Q8 cdeはc&d&eのように聞こえます
これは、ループしていないサンプルでは特に問題になります。
私たちは別の限界に達していないことを願っています...

**Comment by ultrasound1372** [comment]
これはボリュームの変更もサポートされると信じていますか?ADSRのカーブに強制されないボリュームの変更はPSGの効果のために非常に有用であろう。これをマクロと組み合わせて、例えばHuCでドラムを作成することができます。それとも、AYの署名スネア。

**Comment by ultrasound1372** [comment]
@kuma4649この機能の実装によって、ノート エンベロープが破損している可能性があります。構文テストファイル TestArpeggio.gwi は、もはやそれがしたように実行されません。

**Comment by kuma4649** [comment]
musicalmanさん>
キーオンせずにつながっているということでしょうか？

**Comment by kuma4649** [comment]
ultrasound1372さん>
ボリュームもサポート予定です。
＞構文テストファイル TestArpeggio.gwi は、もはやそれがしたように実行されません。
？

**Comment by ultrasound1372** [comment]
量子化されたノートと長いネクタイを含むテストの最初のセットは、ノートがもはや変わらないので、もはや動作していないようです。入力は、アルペジオが適用されていないバーのために保持されているだけです。
The first set of tests involving the quantized notes and then the long tie don't seem to work anymore, as the notes no longer change. The input not is just being held for a bar with no arpeggio being applied.

**Comment by ultrasound1372** [comment]
コンパイラは、AP0とAP1を呼び出す回線で失敗したエラーアルペジオ分析を与えます。構文が変更され、テスト ファイルが更新されていないか。

**Comment by kuma4649** [comment]
あ、コマンドアルペジオではなく、通常のアルペジオの不具合ですね。
調査します。

**Comment by kuma4649** [comment]
現象確認しました。バグ修正しました。
APを指定する前にAPONすると発生するエラーでした。(前回の更新で変更になった正しい動作)
仰るようにsampleが悪いので修正しました。

また、APを指定するだけでAPONするようにしました。
ありがとうございます。

**Comment by musicalman** [comment]
例を送ります。
Q1を使用している部分は問題ありません。
Q0を使用する部分は、キーオフがないため同じように聞こえません。
テスト用にパンアルペジオも含めましたが、それほど重要ではありません。
期待どおりに動作していることを確認したかっただけです。
http://www.fileconvoy.com/dfl.php?id=gaebcbacb41d0f61110002985052c9bf5ca013f93cf

**Comment by ultrasound1372** [comment]
Q0は時計を切り捨てずに意味しませんか?それとも、私は小さなqと混同していますか?

**Comment by ultrasound1372** [comment]
ああ、私はあなたの問題を参照してください、とはい、私はそれがバグだと思います。K053260 を完全長ノートで使用する場合、ノート間のサンプルの適切なキーオフと再起動は行いません。私はK053260テストでもこれを見ましたが、それは最近の開発でした。パンニングギターがジャンプするたびに再起動する前に、今では1つのループで移動します。

**Comment by musicalman** [comment]
qnは、ノートの全長の前にnクロックを解放します。
Qnは、長さのn / 8が経過した後にノートをリリースします。
悲しいことに、私はおそらく少なくとも1、2回は間違ったものを書いたので、混乱があった場合は申し訳ありません。
私の例では、q1を使用してノートを1ティック早くカットしていました。qnは、ノートの全長の前にnクロックを解放します。
Qnは、長さのn / 8が経過した後にノートをリリースします。
私はおそらく少なくとも一度は間違ったものについて書いたことがあります。 混乱があった場合はごめんなさい。

**Comment by ultrasound1372** [comment]
はい、これは別の問題です。そして、それはK053260に固有です、私はC140を使用するようにあなたのファイルを適応させ、q0と同じ問題が発生しません。すべてのノートは、必要に基して再起動されます。

**Comment by kuma4649** [comment]
テスト用のgwiありがとうございます。
いつも助かります。

現象のほう確認しました。修正してみようと思います。
恐らく前回のキーオフが連続で発生するバグを修正したときのものだと思います

**Comment by kuma4649** [comment]
修正しました。ご確認ください

**Comment by musicalman** [comment]
はい、すべてがスムーズに機能しています。

**Comment by kuma4649** [comment]
ボリュームのアルペジオ→未対応

**Comment by kuma4649** [comment]
LFOじゃだめかなぁ。。。

**Comment by musicalman** [comment]
返事が遅くなってごめん。
あなたの言っていることがよくわかりませんでした。
しかし、ボリュームコマンドアルペジオのアイデアは興味深いと思います。

**Comment by ultrasound1372** [comment]
はい、LFOが適切な形状を提供できない場合には必要です。他のいくつかのコマンドと組み合わせることで、チップチューンスネアを作るために使用することができます。特に、ボリュームコマンドがノイズジェネレータを制御する限り、AYで便利です。また、レジスタ書き込み、ノイズ周波数などのより多くのパラメータを操作することができれば、実際には多くのパッチで町に行くことができました。直接音色出力を変更するすべてのコマンドは、これらのコマンドアルペジオに動作することはできませんか?

**Comment by kuma4649** [comment]
>あなたの言っていることがよくわかりませんでした
LFOがボリュームのアルペジオの代わりにはなりませんか
という意味です(^^;

**Comment by kuma4649** [comment]
全てのコマンドというのはかなり大変ですわ。。。
ソースを見ていただくとわかると思うのですが、
ひとつひとつコマンド毎、チップごとにコードを書く必要があり、
そう簡単な作業ではないです。

とりあえずボリュームのアルペジオはそのうち対応したいと考えてますが。。。うーむ。

**Comment by musicalman** [comment]
ああ、わかりました。
ボリュームアルペジオを実装する予定がある場合は、試してみます。
ボリュームアルペジオは私にアイデアを与えました。
ノートのサステイン中に1つのアルペジオを使用し、ノートがリリースされたら、別のアルペジオに切り替えるのがクールです。
リリースは、rコマンドが検出されたとき、またはqまたはQコマンドによって音符が短縮されたときに発生します。
理想的には、サステインとリリースの部分は、/または同様の文字で区切られた同じアルペジオにある可能性があります。
/に遭遇したら、サステインループから抜け出し、リリース部分に切り替えます。
しかし、サステイン用とリリース用の2つのアルペジオを使用する方が簡単な場合は、それも機能します。
うまくいけば、それは理にかなっています。

**Comment by kuma4649** [comment]
Eコマンドのように、リリース時もアルペジオを続行できるようにですね？

**Comment by musicalman** [comment]
はい、Eコマンドのリリースセグメントのように。
リリースに切り替えるときは、前のシーケンスループから抜け出します。
おそらく、サステインとリリースの両方が、独自のループを持つ別々のアルペジオとして扱われる可能性があります。
または、リリースは追加の同期モードである可能性があります。
別の問題：Eとボリュームアルペジオを一緒に使用するとどうなりますか？

**Comment by kuma4649** [comment]
Eとアルペジオは加算するべきでしょうね。。。

**Comment by kuma4649** [comment]
例)
'@ ARP 0 , 1 , q1 , #12 , 0 , | , 3 , -3 , | , 4 , -3
                定義番号0に以下を定義する。
                タイモードを有効にする。gatetimeを1、clock数を12に設定する。
                シフト無しで12clock発音。 
                > ループポイントを設定 
                > 3つ半音を上げて12clock発音 
                > 3つ半音を下げて(元の音程に戻して)12clock発音 
                > 1個目のループポイントに戻る
          KeyOffしたら
                > 4つ半音を上げて12clock発音 
                > 3つ半音を下げて(元の音程に戻して)12clock発音 
                > 2個目のループポイントに戻る

**Comment by kuma4649** [comment]
例)
'@ ARP 0 , v , #12 , 0 , | , 3 , -3 , | , 3 , -4
定義番号0に以下を定義する。
音量モードにする。
> clock数を12に設定する。
> シフト無しで12clock発音。
> 3つ音量を上げて12clock発音
> 3つ音量を下げて(元の音程に戻して)12clock発音
> 1個目のループポイントに戻る
KeyOffしたら
> 3つ半音を上げて12clock発音
> 4つ半音を下げて(元の音程に戻して)12clock発音
> 2個目のループポイントに戻る

**Comment by kuma4649** [comment]
音程と音量だけはとりあえずARPコマンドにて定義。
他のコマンドはCARコマンドにて定義。

**Comment by musicalman** [comment]
私はそれが好きです。
したがって、varコマンドはEコマンドの代替です。
これを実装できれば、より複雑なボリュームエンベロープを作成すると非常に便利です。
それほど重要ではありませんが、arpコマンド内で[]ループを使用する方法を追加できるかどうかも疑問に思いました。
これにより、何かを複数回繰り返すのが簡単になる可能性があります。 したがって、-2、-2、-2、-2、-2 ...と入力する必要はありませんが、代わりに[-2、] 10などを使用できます。
しかし、それは私がタイプしているときに思いついたランダムな考えだったので、それほど重要ではありません。

**Comment by kuma4649** [comment]
実装しました

**Comment by musicalman** [comment]
ありがとう、うまくいっているようです！
しかし、私はバグがあると思いますか？
テストとして、testArpeggio_2.gwiのこの部分を試しました。
'@ VAR 1 0
'@＃6 0 | 3 -3 /＃2 -6
アルペジオの最初の部分は問題ありませんが、キーオフしようとすると音が途切れます。 したがって、/の前の部分だけが聞こえます。
おそらく私は何か間違ったことをしていますか？

**Comment by musicalman** [comment]
また、@ arpコマンドを使用すると、モード2と3が機能しないようです。 コマンドメモに記載されていますが、まだ実装されていないと思います。

**Comment by kuma4649** [comment]
testArpeggio_2.gwiであれば、56行目の
'F1 VP0 [c4r4c4r4]
を
'F1 VP1 [c4r4c4r4]
に変更すると、VAR 1 ～の定義が試せます。
そのままだとVAR 0 ～の定義が使用されます。

@arpのほうは、まだ未実装ですw(忘れてた)

**Comment by kuma4649** [comment]
あと [と]で繰り返しができるようにする機能は今のところ実装する気はありません。
やるとしても、もう少し作りこみができてからかな。。。
実装したくない理由は、処理がいきなり複雑になってしまって混乱しそうだからです。
また、
[と]の中に、|と/を挟んだときどうする
とか決める必要がでてきます。

**Comment by musicalman** [comment]
キーオフについてもう少し調べました。 これが私のgwiファイルです：
'@VAR0,0,|,#6,-1,-1,1,1,/,|,#3,-1
'A1 T120 v15 l4 o4 VP0 crergr

音が切れているようですので、/以降は何も聞こえません
しかし、Ay3チップ（上記のファイルで使用）では、キーオフ中にパチパチという音が聞こえます。 このパチパチという音は、アルペジオの内容によって変化します。
ですから、キーオフ部分は認識されていると思いますが、音が切れすぎてしまいます。

**Comment by kuma4649** [comment]
とりあえず。。。
　|と/は合計2個まで
です。

'@var0,0,|,#6,-1,-1,1,1,/,|,#3,-1
は、3個つかっています。

**Comment by musicalman** [comment]
FM音源では、RRに低い値を使用して、KeeyOff後の音を維持することができます。
次に、ボリュームアルペジオを使用すると、/の後のセクションが聞こえます。
しかし、RRに高い値を使用すると、KeyOff後もサウンドが十分に長く持続しません。 また、他の音源は瞬時にカットされるため、/以降の部分は聞こえません。
したがって、ボリュームアルペジオで/を使用する場合は、新しい音が鳴るまで音源のKeyOffを遅らせたいと思います。
@Eコマンドを使用した場合のKeyOffの遅延と同様です。

**Comment by kuma4649** [comment]
FMの場合は現状の実装のままで良いかなーと思ってます
RRはユーザーが自分で設定するでしょうし。

問題はＡＹのようなソフトエンベロープを必要とする音源でしょうねぇ

**Comment by musicalman** [comment]
そうですね。
ただし、Eコマンドはこの問題を回避します。 そしてそれはまた柔らかい封筒です。
それで、おそらく同じメカニズムをvarで使用できますか？
そうでない場合、ボリュームアルペジオの/部分は制限されます...

**Comment by kuma4649** [comment]
と思ったんですが、いじってみたらmusicalmanさんの方法で十分のようですので
それでいこうと思います。;-P

**Comment by kuma4649** [comment]
https://www.dropbox.com/s/1cnrwha53buc8u4/bin.zip?dl=0

**Comment by kuma4649** [comment]
↑ちょっとためしてみてくださいませ

**Comment by musicalman** [comment]
おかげで、私はそれをテストしました。
私は2つのバグを見つけたと思います。
SN76489は、キーオフ後に続行されません。 音が途切れる。
K053260は、ボリュームアルペジオがアクティブな間は楽器を切り替えることができません。
例はここにあります：http：//www.fileconvoy.com/dfl.php？id = ga8cb5a9715d798201000308368bc324bca73430261
これまでのところ他の問題はありません。

**Comment by kuma4649** [comment]
レポートありがとうございます。
TAG329
で修正しました。

**Comment by kuma4649** [comment]
test k053260.gwiですが、
'@VAR0,0,#4,-2,3,5,4,|,0,|,#2,-1
'S1 r1 T120 l2 v5 VP0 o3 c d e f g r e r
に修正して確認しました。
元のままだと、
・開始音量が大きいため、だんだん大きくなる変化がなくなってしまう。
・RR時のコマンドが「/」の為、変化量が0に戻り、減衰がわかりにくい。
ためです。

**Comment by musicalman** [comment]
ありがとう、修正されました！
今、私はいくつかの楽しみを持って、あなたを気にしないでしょう。

**Comment by kuma4649** [comment]
とじます

**Comment by musicalman** [comment]
2つ、おそらく3つのアルペジオバグを見つけました。
1. K053260では、ボリュームアルペジオがアクティブな場合、サンプルはキーオンされません。
2. rf5c164では、ノートアルペジオ同期モードが0または2の場合、ボリュームアルペジオもアクティブであれば、アルペジオ内のノートはキーオンされません。
3.これまでにテストしたすべてのサウンドチップで、コマンドアルペジオとボリュームアルペジオはノートアルペジオの同期モードを無視しているようです。
つまり、同期モードが0または2の場合、アルペジオのトーンは期待どおりにキーオンされますが、コマンド/ボリュームアルペジオはキーオンされません。
サンプルのgwiデータはここにあります：https：//cp.sync.com/dl/a1b2da750/z4uededs-mdsc36rq-wkwspjg2-5243ekc4

**Comment by kuma4649** [comment]
ありがとうございます。
調査しまーす

**Comment by kuma4649** [comment]
音量アルペジオは同期モードは、存在しません。
また、音程アルペジオのモードを他のアルペジオが参照することはありません。

コマンドアルペジオにはSyncという同期モードがありますが、
これもコマンドアルペジオのみの話であって、他のアルペジオがそれを参照することはありません

**Comment by musicalman** [comment]
説明をありがとう。
あなたが説明するように物事は今行動しているようです！

**Comment by musicalman** [comment]
@arpコマンドを使用しているときに何か他のものを見つけました。
アルペジオデータでqnまたはQnを使用すると、ノートは以前のようにキーオフされません。
FMトーンはコマンドに従ってキーオフするように見えますが、@ Eまたはボリュームアルペジオはキーオフしません。
少なくとも私が使ったサウンドチップでは。

例：
'@ARP0,0,#24,q6,0,|,2,2,1,2,2,2,1,-12
'@VAR0,0,#5,0,|,-1,/,#1,-3,-2,-2,-2,-2,-2
'@E1,14,0,5,8,1,1,1,Ay3
'A1 T120 v14 l1 AP0 VP0 o4 c VPOF @E1 c1 EOF

この例では、エンベロープは早期にキーオフされませんが、古いバージョンではキーオフされました。
どのバージョンが変更を導入したかはまだ調査していません。
バグですか？

**Comment by kuma4649** [comment]
バージョンの番号はわかりますか？

**Comment by musicalman** [comment]
まだですが、後で古いバージョンに戻ります。

**Comment by musicalman** [comment]
アルペジオの振る舞いが変わったところを見つけました！
TAG 352では、ノートは期待どおりにリリースされますが、TAG353ではリリースされません。
その時、あなたは私の以前の報告に応えて、新しいノートでエンベロープとボリュームアルペジオをリセットしました。
ただし、qnコマンドとQnコマンドはアルペジオ内で機能しなくなりました。

**Comment by kuma4649** [comment]
ありがとうございます！助かります！

**Comment by kuma4649** [comment]
TAG361で修正しました。ご確認ください。

**Comment by musicalman** [comment]
いいですね、今のところ問題は発生していません。

**Comment by musicalman** [comment]
いいですね、今のところ問題は発生していません。

**Comment by musicalman** [comment]
ボリュームアルペジオでもう1つ見つけました。 多分それはバグです。
徐々に音がフェードアウトするボリュームアルペジオを作ろうとしていますが、key offで止めることができます。 おそらく私はそれを正しくやっていないのですか？
問題は、key offが遅すぎるか、まったく発生しない場合があることです。
＃で指定されたクロック数が経過するまで、key offは発生しないようです。
gwiデータ：

'@VAR0,0,#3,15,-2,-2,#20,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,/,0 e
'S1 T120 l4 o3 v0 
bug:
'S1 VP0 Q5 c d e f g a b >c

また、これがバグである場合は、@ arpコマンドを確認することを忘れないでください。

**Comment by kuma4649** [comment]
keyoffのタイミングでアルペジオの処理は
'/'
の位置に移動します。
そこで変化量0のまま、アルペジオは終了するので
音が出続ける状態になります。

**Comment by musicalman** [comment]
申し訳ありませんが、理解できないと思います...
奇妙なことを説明させてください。
gwiファイルのQ5をQ4に変更したところ、期待どおりに音符がカットされました。
しかし、Q5を使用すると、音符が切れません。
アルペジオを変更した場合、たとえば＃20を＃18に変更した場合、音符はカットされますが、遅れます。

**Comment by kuma4649** [comment]
うーん、、、わからないのでmmlを提示してもらえませんでしょうか

**Comment by musicalman** [comment]
ここからダウンロード：
https://cp.sync.com/dl/a2ae279b0/rg25wye9-jur89xc4-6tbw5qpz-kxkj2d7j
mmlデータを調整したので、動作は明らかです。

**Comment by kuma4649** [comment]
ありがとうございます！
バグ確認できました！

**Comment by musicalman** [comment]
良い知らせと悪い知らせがあります。
TAG378では、バグが修正されました！
ただし、残念ながら、@ arpコマンドを使用すると返されます。
以前に送信したgwiデータを変更して、代わりに@arpを使用しました。
https://cp.sync.com/dl/f05377ca0/vvie3aaw-s7gnfdf7-5np5mjrh-as6mwmpw

**Comment by musicalman** [comment]
素晴らしい、TAG379はそれを修正しました！

**Comment by musicalman** [comment]
こんにちは、
アルペジオで別のバグを見つけたと思います：
HuCでボリュームとトーンのアルペジオを一緒に使用しようとしています。
音量と音色の両方が同時に変化する場合、それはうまく機能します。
ただし、音量とトーンの変更が非同期の場合、音量が正しく設定されていないことがあります。 ボリュームアルペジオに固執するのではなく、vコマンドの値に設定されます。
次に例を示します。
https://cp.sync.com/dl/fb9d5b980/f8at2ehq-6ye5cdbc-9u6tuezy-ef7f847s

**Comment by kuma4649** [comment]
bugにみえません...
v0VP1
のほうは、0の音量に31を加算してから-1をどんどん加算してますよね。。。

**Comment by kuma4649** [comment]
あ、わかりました。
音色が切り替わったタイミングで音量が再設定されてしまうということですね？
↓こんな感じで試したらわかりました。
'@CAR0,@,0,#48,0,1,E
'H1 CA0,0v31 VP0 o5 c1

**Comment by musicalman** [comment]
はい、トーンが変わると音量がリセットされます。
あなたの例では、トーンが変わると、音量はアルペジオのレベルにとどまるのではなく、v31まで上がりました。
K051649にはこのバグがないので、ここで簡単に解決できることを願っています。

**Comment by kuma4649** [comment]
TAG396にて対応しました。

**Comment by musicalman** [comment]
修正されたようです。 再度、感謝します！

**Comment by musicalman** [comment]
修正されたようです。 再度、感謝します！

**Comment by ultrasound1372** [comment]
@kuma4649 私は彼らがノイズをサポートしている今、コマンドアルペジオでいくつかのAYドラムを作ろうとしています。私が抱えている問題は、コンパイラがこれをコンパイルしようとしたときに永久にフリーズするように見えることです。
```
'@ ARP 0, 3, #1 | 12
'@ E 0, 0, 0, 1, 0, 1, 0, 1,AY10
'@ CAR 0,P,0, #2 2 #3 3 | 2
'@ CAR 1,w,0 #1 1 1 2 3 | 4
'A1 l8 o3 @0 CA0,0 CA1,1 CAON0 CAON1 AP0 APON a8 CAOF0 CAOF1 APOF
```

**Comment by kuma4649** [comment]
原因は、「,で区切っていない」ということになりますね...

**Comment by kuma4649** [comment]
只、そのミスの影響でコンパイルが無限ループに陥ってしまうのはまずいのでそこは修正しようと思います。

**Comment by kuma4649** [comment]
更に、空白も区切り文字として使用できるようにします。

**Comment by ultrasound1372** [comment]
@kuma4649 アルペジオの存在下ではキーオフが正しく動作しないようです。私はいくつかのエイリアスドラムを作ったが、私はキックドラムは、そのノートが終了した後に、それに続く残りの部分を通して持続することに気づいた。なぜこれがなのか知っていますか?
```
'@ ARP 0, 3, #1, | ,15
'@ E 0, 0, 0, 1, 0, 1, 0, 1,AY10
'@ E 1, 0, 0, 1, 0, 1, 0, 2,AY10
'@ ARP 1, 3, #1, 50,70,90,|,100
'@ CAR 0,P,0, #1, 2, 3, 1, 1, 3, |, 2
'@ CAR 1,w,0,#1,1,3,5
'@ VAR 0,0, #2,0,-1,0,-3,-4,-5,|,-2
'@ VAR 1,0,#1,-1,|,-2
'@ VAR 2,0,#2,|,-1
'%sd VP0 VPON CA0,0 CA1,1 CAON0 CAON1 AP0 APON a16 CAOF0 CAOF1 APOF VPOF P1
'%hc P2 w0 VP1 VPON c16 VPOF P1
'%k VP2 VPON AP1 APON c16 APOF VPOF
'A1 l8 o3 [%kr.%sdr.%kr16%hc%hc%sdr.]2
```

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/117288405-6eb39880-aea6-11eb-9c3b-8f17db8a3cd7.png)

VPOFを行うことにより、ボリュームアルペジオの処理を途中で打ち切るから。
と思います。

**Comment by kuma4649** [comment]
TAG426でAPOF/VPOFするとキーオフするようにしてみました。

**Comment by ultrasound1372** [comment]
APOF / VPOFですぐにキーオフすることが望まれる行動になるかどうかはわかりませんが、私が行ったとき、私はそれらをオンにする前の状態にリセットされると仮定しました。ノートの実際のキーオフが残りの部分を超えて延長されているのは、それがどのように起こったのか分かりませんが、AYのキーイングの一形態として音量を0に設定していますか?

**Comment by ultrasound1372** [comment]
これは私がどんな場合にも抱えていた問題を解決します。
