### ISSUE TITLE
HuC6280 unable to pan

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#72]
ご迷惑をおかけして申し訳ありませんが、バグを発見したと思います。
チャンネルのパンを調整しようとしていますが、うまくいきません。 音はモノラルのままです。
私のgwiファイルは次のようになります。
'@H0,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
'H1 T120 o3 @0 p12,4 cege
私は何か間違ったことをしていますか？

**Comment by kuma4649** [comment]
現象確認しました。しゅうせいしますー

**Comment by kuma4649** [comment]
すみません、すっかり忘れていたのですが、TAG315で対応済みみたいです。
ご確認ください

**Comment by kuma4649** [comment]
閉じます

**Comment by musicalman** [comment]
はい、少し前に修正されていることに気づきましたが、確認も完全に忘れていました。
気をつけて直していただきありがとうございます。
