### ISSUE TITLE
Y8950 Support?

### ISSUE THREAD

**Issue by pedipanol** [kuma4649/mml2vgm#73]
Y8950のサウンドチップのサポートを追加してもらえませんか？OPLと同じですが、4ビットADPCMチャンネルも搭載しています。
MSX-AUDIOの音楽を作るのにいいと思います。(DeepL翻訳)

**Comment by kuma4649** [comment]
対応していたような…
鍵盤でしょうか

**Comment by kuma4649** [comment]
おまたせー

**Comment by kuma4649** [comment]
閉じますね...
