### ISSUE TITLE
rf5c and qsound bugs

### ISSUE THREAD

**Issue by musicalman** [kuma4649/mml2vgm#74]
rf5c164とQsoundのバグを見つけました。 1つの投稿にたくさん入れてすみません。
Rf5C：
前のエンベロープの有効期限がまだ切れていない場合、インストゥルメントとボリュームエンベロープを同時に変更するとバグが発生します。
具体的には、サンプルが正しく切り替わらない。
トーンアルペジオの場合はどうなるのかわかりません。

QSound
一部のサンプルは非常に歪んでいます。 使用するサンプルやロードする順番によって歪みが変化するようです。
また、ループの最初と最後で別の楽器を使用したい場合は、ループに到達したときに破損した音が聞こえる場合があります。
ここに例があります。
http://www.fileconvoy.com/dfl.php?id=g5c1a813e3cd459d41000305282f4336d77b58048e2

**Comment by kuma4649** [comment]
いつも、ありがとうございます！
後で順番に調査させていただきますね。

**Comment by kuma4649** [comment]
修正しましたのでお確かめくださいませ。

**Comment by musicalman** [comment]
ありがとう、バグは修正されたようです！
