### ISSUE TITLE
AY-3-8910を2MHzに対応してほしい

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/mml2vgm#77]
Atari系やYM2149Fなど互換ICは入力周波数が2MHzやエンヴェロープが5bitになっているので、そのチップでAY向けに作成されたVGMを再生するとピッチが狂います。

VGMヘッダにはAYのチップ選択があるみたいなのでそれも活用するほうがいいかもです。

**Comment by kuma4649** [comment]
とりあえずマスタークロック変更機能だけ実装しました

**Comment by kuma4649** [comment]
CHIPTYPE,FLAGSも直で指定する感じにしてみました

**Comment by kuma4649** [comment]
どうでした？

**Comment by kuma4649** [comment]
とじますね。
