### ISSUE TITLE
Cracks appear when playing notes

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#80]
It feels weird, because no matter which audio output method I use, every time a note is activated, it seems to have broken sound

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/107110768-8c606a00-6885-11eb-85bc-68360efc1b40.mp4

This phenomenon occurs from time to time

**Comment by kuma4649** [comment]
？？？

**Comment by denjhang** [comment]
It seems to be a problem with sound buffering. When the notes are played, sometimes the sound breaks suddenly.

**Comment by kuma4649** [comment]
動画を見る限り、問題なさそうですが。。。
とりあえず、処理の速いWasapi或いはASIOのデバイスを選択してみてください。

**Comment by denjhang** [comment]
ok.Maybe my computer performance is too poor

**Comment by kuma4649** [comment]
重い処理で申し訳ないです。
