### ISSUE TITLE
Find and replace function

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#82]

**Comment by kuma4649** [comment]
findはあったような？

**Comment by musicalman** [comment]
Isn't the alias function like find and replace?

**Comment by kuma4649** [comment]
[F3]key?

**Comment by denjhang** [comment]
I know that the Find function is available. What is needed is to add a replacement function

**Comment by kuma4649** [comment]
置換機能を追加しましたので閉じますね
