### ISSUE TITLE
Something went wrong with ym2612x

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#83]
![截图未命名210206203653](https://user-images.githubusercontent.com/61811583/107118375-9d2bd280-68bb-11eb-98c3-94c55043f3ee.jpeg)

**Comment by kuma4649** [comment]
？？？？

**Comment by denjhang** [comment]
![截图未命名210206203653](https://user-images.githubusercontent.com/61811583/107118522-8f2a8180-68bc-11eb-9b7c-1ffe62af6a32.jpeg)

**Comment by kuma4649** [comment]
理解しました。
「e」に音色が割り当てられていません。

**Comment by denjhang** [comment]
ok
