### ISSUE TITLE
Can the volume of YM2612X 4ch PCM be adjusted independently?

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#84]
'E06 T126 m1
'E06   v120 o4 l4 Q4 mon @0 cdcd mof cdcd

'E10 T126 m1
'E10   v70 o4 l4 Q4 mon @0 r16cdcd mof cdcd

These two channels sound the same

**Comment by kuma4649** [comment]
XGMのPCMは音量は指定できません。

**Comment by denjhang** [comment]
ok
