### ISSUE TITLE
Traceplay does not properly follow notes in mml2vgmIDE

### ISSUE THREAD

**Issue by YoshiLightStar** [kuma4649/mml2vgm#91]
**Describe the bug**
The Traceplay doesn't seem to follow the notes as it should

**To Reproduce**
1. Create a PMD MML document
2. Write notes in
3. Play with Traceplay
4. The Traceplay doesn't seem to follow the notes as it should

**Expected behavior**
The Traceplay should follow the notes

**GIF of issue**
![2021-02-14 15-34-36](https://user-images.githubusercontent.com/16447892/107888526-bdbae480-6eda-11eb-9c5f-ea96c53f91d0.gif)

**Info**
 - OS: Windows 7 SP1
 - mml2vgmIDE: TAG363

**Comment by kuma4649** [comment]
返事遅くなりまして申し訳ありません。
恐らく、7行目の改行をcrlfに変更すると
解決すると思われます。

**Comment by kuma4649** [comment]
とじますね。必要であればまた開いてください
