### ISSUE TITLE
VAL-SOUND?

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#94]
![截图未命名0313005327](https://user-images.githubusercontent.com/61811583/110973073-b848a100-8397-11eb-941d-6ba55f3a6f41.jpeg)
What does it mean？

**Comment by kuma4649** [comment]
FM(OPN)の音色のデータをVAL-SOUNDさんからもらってくる機能です。
インターネットなどに繋がっていないと、データを受け取る処理に失敗して
エラーメッセージを表示します。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね？
