### ISSUE TITLE
What is "sien"

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#95]
![截图未命名0313005854](https://user-images.githubusercontent.com/61811583/110973205-e5954f00-8397-11eb-8fc4-d065c2c40b6e.jpeg)
I clicked the OPN instrument and nothing happened

**Comment by kuma4649** [comment]
入力を支援する機能です。
書式がややこしいコマンドのテンプレートを挿入したり、選択した音色を挿入したり出来ます。

**Comment by kuma4649** [comment]
とじますね。
