### ISSUE TITLE
Suggest built-in xgmtool

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#96]
Use xgmtool to directly convert xgm to vgm
https://github.com/Stephane-D/SGDK/tree/master/bin

**Comment by kuma4649** [comment]
??

**Comment by denjhang** [comment]
I suggest mml2vgmIDE has built-in xgmtool, which can easily make YM2612X output VGM

**Comment by kuma4649** [comment]
いえ、xgmのままで十分です。。。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
ご期待に沿えず申し訳ございません。orz
