### ISSUE TITLE
Can you provide an option to permanently close this pop-up window

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#97]
![截图未命名210327232442](https://user-images.githubusercontent.com/61811583/112725617-1c509500-8f54-11eb-88c0-470fbe2f255a.jpeg)
I clicked Cancel, but it will pop up again the next time I start it, which is a bit annoying.

**Comment by kuma4649** [comment]
ちょうさしまーす

**Comment by kuma4649** [comment]
TAG388にて対応しました

**Comment by kuma4649** [comment]
とじますね。
