### ISSUE TITLE
Is it possible to build-in NRTDRV.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/mml2vgm#98]
![截图未命名210327232659](https://user-images.githubusercontent.com/61811583/112725698-8b2dee00-8f54-11eb-86e0-7588b644e66c.jpeg)

**Comment by kuma4649** [comment]
？？pmdでは？

**Comment by kuma4649** [comment]
NRTDRVのサポートを行う予定はないです。

**Comment by denjhang** [comment]
ok
